using verii_wms_api_v2.Modules.WarehouseOutbound.Domain;
using verii_wms_api_v2.Modules.WarehouseOperations.Domain;
using verii_wms_api_v2.Shared;

namespace verii_wms_api_v2.Modules.WarehouseOutbound.Application;

public sealed record WarehouseOutboundSourceRequest(string OrderNumber,string ExternalLineId,int? ExternalLineNo,string ExternalStockCode,string? ExternalYapCode,DateOnly? OrderDate,decimal OrderedQuantity,decimal PreviouslyShippedQuantity,decimal AvailableQuantity);
public sealed record WarehouseOutboundTrackingRequest(decimal Quantity,string? HandlingUnitNo,string? ContainerNo,string? LotNo,string? SerialNo,DateOnly? ManufacturingDate,DateOnly? ExpirationDate,long? SourceLocationId);
public sealed record WarehouseOutboundLineRequest(long StockId,long? YapCodeId,decimal Quantity,string? UnitCode,StockTrackingType TrackingType,bool RequireHandlingUnit,long? SourceLocationId,string? Description,IReadOnlyList<WarehouseOutboundTrackingRequest>? Trackings,WarehouseOutboundSourceRequest? Source);
public sealed record CreateWarehouseOutboundDraftRequest(Guid IdempotencyKey,string BranchCode,long DocumentSeriesId,DateOnly DocumentDate,WarehouseOutboundInitiationMode InitiationMode,long CustomerId,long SourceWarehouseId,long? StagingLocationId,long? LoadingLocationId,DateTimeOffset? PlannedWarehouseOutboundAtUtc,byte Priority,string? ExternalReferenceNo,bool IsEDispatch,string? CarrierCode,string? CarrierName,string? VehiclePlate,string? TrailerPlate,string? DriverName,string? SealNo,string? Description,IReadOnlyList<WarehouseOutboundLineRequest> Lines,IReadOnlyList<long>? AssignedUserIds);
public sealed record CreateWarehouseOutboundDraftResult(long Id,string DocumentNo,int LineCount,decimal RequestedQuantity,bool Replayed,long? TaskId,string? TaskNo);
public sealed record UpdateWarehouseOutboundDraftRequest(string RowVersion,DateOnly DocumentDate,long? StagingLocationId,long? LoadingLocationId,
    DateTimeOffset? PlannedWarehouseOutboundAtUtc,byte Priority,string? ExternalReferenceNo,bool IsEDispatch,string? CarrierCode,
    string? CarrierName,string? VehiclePlate,string? TrailerPlate,string? DriverName,string? SealNo,string? Description);
public sealed record WarehouseOutboundGridRow(long Id,string BranchCode,string DocumentNo,DateOnly DocumentDate,WarehouseOutboundInitiationMode InitiationMode,WarehouseOutboundStatus Status,OperationApprovalStatus ApprovalStatus,ErpIntegrationStatus ErpIntegrationStatus,long CustomerId,string CustomerCode,string? CustomerName,long SourceWarehouseId,int SourceWarehouseCode,string SourceWarehouseName,int LineCount,decimal RequestedQuantity,decimal PickedQuantity,decimal PackedQuantity,decimal LoadedQuantity,decimal ShippedQuantity,byte Priority,DateTimeOffset? PlannedWarehouseOutboundAtUtc,long? CreatedBy,DateTime? CreatedDate,long? UpdatedBy,DateTime? UpdatedDate);
public sealed record WarehouseOutboundDetailLine(long Id,int LineNo,long StockId,string StockCode,string? StockName,string? YapCode,string UnitCode,decimal RequestedQuantity,decimal ReservedQuantity,decimal PickedQuantity,decimal PackedQuantity,decimal LoadedQuantity,decimal ShippedQuantity,WarehouseOutboundLineStatus Status,int TrackingCount,StockTrackingType TrackingType,bool RequireHandlingUnit);
public sealed record WarehouseOutboundDraftMetadata(long? StagingLocationId,long? LoadingLocationId,string? ExternalReferenceNo,bool IsEDispatch,
    string? CarrierCode,string? CarrierName,string? VehiclePlate,string? TrailerPlate,string? DriverName,string? SealNo,string? Description);
public sealed record WarehouseOutboundDetail(WarehouseOutboundGridRow Header,IReadOnlyList<WarehouseOutboundDetailLine> Lines,string RowVersion,WarehouseOutboundDraftMetadata Draft);
public interface IWarehouseOutboundService{Task<CreateWarehouseOutboundDraftResult>CreateDraftAsync(CreateWarehouseOutboundDraftRequest request,long actor,CancellationToken ct=default);Task<PagedResponse<WarehouseOutboundGridRow>>GetPagedAsync(PagedRequest request,CancellationToken ct=default);Task<WarehouseOutboundDetail>GetDetailAsync(long id,CancellationToken ct=default);Task<WarehouseOutboundDetail>UpdateDraftAsync(long id,UpdateWarehouseOutboundDraftRequest request,long actor,CancellationToken ct=default);Task DeleteDraftAsync(long id,long actor,CancellationToken ct=default);}

public sealed record WarehouseOutboundPolicyDto(long Id,string BranchCode,bool AllowOrderBasedTask,bool AllowStockBasedTask,bool AllowOrderBasedDirect,bool AllowStockBasedDirect,bool RequireApproval,bool RequireAssigneeForTask,bool AllowMultipleAssignees,bool AutoReleaseTaskBased,bool AllowPartialPicking,bool AllowPartialWarehouseOutbound,bool RequireSourceLocation,bool RequireWarehouseOutboundInformation,bool RequireLoadingConfirmation,bool AutoPostErpAfterApproval,decimal MinimumFulfillmentPercent,decimal OverPickTolerancePercent,WarehouseOutboundReservationPolicy ReservationPolicy,WarehouseOutboundPackingPolicy PackingPolicy,WarehouseOutboundShortagePolicy ShortagePolicy,WarehouseOutboundOverPickPolicy OverPickPolicy,long? UpdatedBy,DateTime? UpdatedDate);
public sealed record UpdateWarehouseOutboundPolicyRequest(string BranchCode,bool AllowOrderBasedTask,bool AllowStockBasedTask,bool AllowOrderBasedDirect,bool AllowStockBasedDirect,bool RequireApproval,bool RequireAssigneeForTask,bool AllowMultipleAssignees,bool AutoReleaseTaskBased,bool AllowPartialPicking,bool AllowPartialWarehouseOutbound,bool RequireSourceLocation,bool RequireWarehouseOutboundInformation,bool RequireLoadingConfirmation,bool AutoPostErpAfterApproval,decimal MinimumFulfillmentPercent,decimal OverPickTolerancePercent,WarehouseOutboundReservationPolicy ReservationPolicy,WarehouseOutboundPackingPolicy PackingPolicy,WarehouseOutboundShortagePolicy ShortagePolicy,WarehouseOutboundOverPickPolicy OverPickPolicy);
public interface IWarehouseOutboundPolicyService{Task<WarehouseOutboundPolicyDto>GetAsync(string branchCode,CancellationToken ct=default);Task<WarehouseOutboundPolicyDto>UpdateAsync(UpdateWarehouseOutboundPolicyRequest request,long actor,CancellationToken ct=default);}
