namespace verii_wms_api_v2.Modules.WarehouseAssistant.Localization;

public sealed class WarehouseAssistantResource;

public static class WarehouseAssistantMessageKeys
{
    public const string CapabilityExampleMyActivities = nameof(CapabilityExampleMyActivities);
    public const string CapabilityExampleUserActivities = nameof(CapabilityExampleUserActivities);
    public const string CapabilityExampleSerialBalance = nameof(CapabilityExampleSerialBalance);
    public const string CapabilityExampleStockBalance = nameof(CapabilityExampleStockBalance);
    public const string CapabilityExampleSerialReceipt = nameof(CapabilityExampleSerialReceipt);
    public const string CapabilityExampleBarcode = nameof(CapabilityExampleBarcode);
    public const string CapabilityExampleMovement = nameof(CapabilityExampleMovement);
    public const string CapabilityExampleTasks = nameof(CapabilityExampleTasks);
    public const string ScopeAll = nameof(ScopeAll);
    public const string ScopeSelf = nameof(ScopeSelf);
    public const string ActivityNone = nameof(ActivityNone);
    public const string ActivityFound = nameof(ActivityFound);
    public const string ActivityForcedSelf = nameof(ActivityForcedSelf);
    public const string SerialBalanceDenied = nameof(SerialBalanceDenied);
    public const string SerialRequired = nameof(SerialRequired);
    public const string SerialBalanceNone = nameof(SerialBalanceNone);
    public const string SerialBalanceFound = nameof(SerialBalanceFound);
    public const string SerialReceiptDenied = nameof(SerialReceiptDenied);
    public const string SerialReceiptRequired = nameof(SerialReceiptRequired);
    public const string SerialReceiptNone = nameof(SerialReceiptNone);
    public const string SerialReceiptFound = nameof(SerialReceiptFound);
    public const string StockBalanceDenied = nameof(StockBalanceDenied);
    public const string StockRequired = nameof(StockRequired);
    public const string StockBalanceNone = nameof(StockBalanceNone);
    public const string StockBalanceFound = nameof(StockBalanceFound);
    public const string HelpAnswer = nameof(HelpAnswer);
    public const string UnknownAnswer = nameof(UnknownAnswer);
    public const string AllUsers = nameof(AllUsers);
    public const string ConversationNotFound = nameof(ConversationNotFound);
    public const string DateToday = nameof(DateToday);
    public const string DateYesterday = nameof(DateYesterday);
    public const string DateLastSevenDays = nameof(DateLastSevenDays);
    public const string DateThisWeek = nameof(DateThisWeek);
    public const string DateLastThirtyDays = nameof(DateLastThirtyDays);
    public const string UserNumber = nameof(UserNumber);
    public const string SystemUser = nameof(SystemUser);
    public const string Unassigned = nameof(Unassigned);
    public const string ActionGoodsReceipt = nameof(ActionGoodsReceipt);
    public const string ActionWarehouseTransfer = nameof(ActionWarehouseTransfer);
    public const string ActionProductionTransfer = nameof(ActionProductionTransfer);
    public const string ActionShipment = nameof(ActionShipment);
    public const string ActionWarehouseInbound = nameof(ActionWarehouseInbound);
    public const string ActionWarehouseOutbound = nameof(ActionWarehouseOutbound);
    public const string ActionQuality = nameof(ActionQuality);
    public const string ActionPacking = nameof(ActionPacking);
    public const string ActionStock = nameof(ActionStock);
    public const string ActionUser = nameof(ActionUser);
    public const string MessageRequired = nameof(MessageRequired);
    public const string MessageTooLong = nameof(MessageTooLong);
    public const string BarcodeBalanceDenied = nameof(BarcodeBalanceDenied);
    public const string BarcodeRequired = nameof(BarcodeRequired);
    public const string BarcodeResolverUnavailable = nameof(BarcodeResolverUnavailable);
    public const string BarcodeRetrySuggestion = nameof(BarcodeRetrySuggestion);
    public const string BarcodeBalanceNone = nameof(BarcodeBalanceNone);
    public const string BarcodeBalanceFound = nameof(BarcodeBalanceFound);
    public const string MovementDenied = nameof(MovementDenied);
    public const string MovementSubjectRequired = nameof(MovementSubjectRequired);
    public const string MovementNone = nameof(MovementNone);
    public const string MovementFound = nameof(MovementFound);
    public const string SerialSubject = nameof(SerialSubject);
    public const string SuggestionStockMovement = nameof(SuggestionStockMovement);
    public const string SuggestionSerialBalance = nameof(SuggestionSerialBalance);
    public const string SuggestionStockLocation = nameof(SuggestionStockLocation);
    public const string TaskDenied = nameof(TaskDenied);
    public const string TaskNone = nameof(TaskNone);
    public const string TaskFound = nameof(TaskFound);
    public const string TaskForcedSelf = nameof(TaskForcedSelf);
    public const string InvalidSession = nameof(InvalidSession);
    public const string BranchScopeMissing = nameof(BranchScopeMissing);
}
