// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using verii_wms_api_v2.Modules.Identity.Infrastructure;

#nullable disable

namespace verii_wms_api_v2.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    [Migration("20260722095912_AddImmutableStockMovementLedger")]
    partial class AddImmutableStockMovementLedger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("verii_wms_api_v2.Modules.AccessControl.Domain.PermissionDefinition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AvailableOnMobile")
                        .HasColumnType("bit");

                    b.Property<bool>("AvailableOnWeb")
                        .HasColumnType("bit");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("IsDeleted");

                    b.ToTable("RII_PERMISSION_DEFINITIONS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "SYSTEM.USERS.VIEW",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kullanıcıları Görüntüle"
                        },
                        new
                        {
                            Id = 1002L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "SYSTEM.USERS.MANAGE",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kullanıcıları Yönet"
                        },
                        new
                        {
                            Id = 1003L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "SYSTEM.PERMISSIONS.VIEW",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "İzinleri Görüntüle"
                        },
                        new
                        {
                            Id = 1004L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "SYSTEM.PERMISSIONS.MANAGE",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "İzinleri Yönet"
                        },
                        new
                        {
                            Id = 1005L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "SYSTEM.SMTP.MANAGE",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "SMTP Ayarlarını Yönet"
                        },
                        new
                        {
                            Id = 1006L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "SYSTEM.HANGFIRE.VIEW",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hangfire İzle"
                        },
                        new
                        {
                            Id = 1007L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "SYSTEM.HANGFIRE.TRIGGER",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hangfire Job Tetikle"
                        },
                        new
                        {
                            Id = 1008L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "SYSTEM.AUDIT.VIEW",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Audit Kayıtlarını Görüntüle"
                        },
                        new
                        {
                            Id = 1009L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "WMS.LOCATIONS.VIEW",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Raf Tanımlarını Görüntüle"
                        },
                        new
                        {
                            Id = 1010L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "WMS.LOCATIONS.CREATE",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Raf Tanımı Oluştur"
                        },
                        new
                        {
                            Id = 1011L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "WMS.LOCATIONS.UPDATE",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Raf Tanımını Güncelle"
                        },
                        new
                        {
                            Id = 1012L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "WMS.LOCATIONS.DELETE",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Raf Tanımını Sil"
                        },
                        new
                        {
                            Id = 1013L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "WMS.STOCK_MOVEMENTS.VIEW",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Stok Hareketlerini Görüntüle"
                        },
                        new
                        {
                            Id = 1014L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "WMS.STOCK_MOVEMENTS.POST",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Stok Hareketi Kaydet"
                        },
                        new
                        {
                            Id = 1015L,
                            AvailableOnMobile = false,
                            AvailableOnWeb = true,
                            BranchCode = "0",
                            Code = "WMS.STOCK_MOVEMENTS.REVERSE",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Stok Hareketini Ters Çevir"
                        });
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.AccessControl.Domain.PermissionGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystemAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("RII_PERMISSION_GROUPS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tam sistem yönetimi",
                            IsActive = true,
                            IsDeleted = false,
                            IsSystemAdmin = true,
                            Name = "System Administrators"
                        });
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.AccessControl.Domain.PermissionGroupPermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("PermissionDefinitionId")
                        .HasColumnType("bigint");

                    b.Property<long>("PermissionGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PermissionDefinitionId");

                    b.HasIndex("PermissionGroupId", "PermissionDefinitionId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("RII_PERMISSION_GROUP_PERMISSIONS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1001L,
                            PermissionGroupId = 1001L
                        },
                        new
                        {
                            Id = 1002L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1002L,
                            PermissionGroupId = 1001L
                        },
                        new
                        {
                            Id = 1003L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1003L,
                            PermissionGroupId = 1001L
                        },
                        new
                        {
                            Id = 1004L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1004L,
                            PermissionGroupId = 1001L
                        },
                        new
                        {
                            Id = 1005L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1005L,
                            PermissionGroupId = 1001L
                        },
                        new
                        {
                            Id = 1006L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1006L,
                            PermissionGroupId = 1001L
                        },
                        new
                        {
                            Id = 1007L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1007L,
                            PermissionGroupId = 1001L
                        },
                        new
                        {
                            Id = 1008L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1008L,
                            PermissionGroupId = 1001L
                        },
                        new
                        {
                            Id = 1009L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1009L,
                            PermissionGroupId = 1001L
                        },
                        new
                        {
                            Id = 1010L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1010L,
                            PermissionGroupId = 1001L
                        },
                        new
                        {
                            Id = 1011L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1011L,
                            PermissionGroupId = 1001L
                        },
                        new
                        {
                            Id = 1012L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1012L,
                            PermissionGroupId = 1001L
                        },
                        new
                        {
                            Id = 1013L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1013L,
                            PermissionGroupId = 1001L
                        },
                        new
                        {
                            Id = 1014L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1014L,
                            PermissionGroupId = 1001L
                        },
                        new
                        {
                            Id = 1015L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionDefinitionId = 1015L,
                            PermissionGroupId = 1001L
                        });
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.AccessControl.Domain.UserPermissionGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("PermissionGroupId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PermissionGroupId");

                    b.HasIndex("UserId", "PermissionGroupId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("RII_USER_PERMISSION_GROUPS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1001L,
                            BranchCode = "0",
                            CreatedDate = new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            PermissionGroupId = 1001L,
                            UserId = 1L
                        });
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.Audit.Domain.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0");

                    b.Property<string>("ChangedFieldsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValuesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedByUserEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long?>("PerformedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("TraceId")
                        .HasDatabaseName("IX_RII_AUDIT_LOGS_TraceId");

                    b.HasIndex("PerformedByUserId", "CreatedDate")
                        .HasDatabaseName("IX_RII_AUDIT_LOGS_User_CreatedDate");

                    b.HasIndex("EntityType", "EntityId", "CreatedDate")
                        .HasDatabaseName("IX_RII_AUDIT_LOGS_Entity_CreatedDate");

                    b.HasIndex("Source", "ActionType", "CreatedDate")
                        .HasDatabaseName("IX_RII_AUDIT_LOGS_Source_Action_CreatedDate");

                    b.ToTable("RII_AUDIT_LOGS", (string)null);
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.Customer.Domain.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0");

                    b.Property<short>("BusinessUnitCode")
                        .HasColumnType("smallint");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerName")
                        .HasDatabaseName("IX_Customer_CustomerName");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("BranchCode", "CustomerCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Customer_BranchCode_CustomerCode")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("RII_CUSTOMER", (string)null);
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.Identity.Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("RII_USERS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "admin@v3rii.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$/miyTaLTVkU0keOJabjkQ.bKF4Rb6a2jhuLWDz67I4LLxjwWQ6IJW",
                            Role = "superadmin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.Identity.Domain.UserDetail", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("UserId");

                    b.ToTable("RII_USER_DETAILS", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            FirstName = "System",
                            LastName = "Administrator"
                        });
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.Location.Domain.WarehouseLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AisleNo")
                        .HasColumnType("int");

                    b.Property<bool>("AllowCycleCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowMixedLot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("AllowMixedStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("AllowMixedStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Barcode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BarcodeEntryMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Auto");

                    b.Property<int?>("BinNo")
                        .HasColumnType("int");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0");

                    b.Property<decimal?>("CapacityQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("CapacityUnit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("CapacityVolume")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("CapacityWeight")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPickable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPutaway")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsQuarantine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LevelNo")
                        .HasColumnType("int");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Cell");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long?>("ParentLocationId")
                        .HasColumnType("bigint");

                    b.Property<int?>("RackNo")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.Property<string>("ZoneCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("UX_RII_LOCATION_BARCODE")
                        .HasFilter("[Barcode] IS NOT NULL AND [IsDeleted] = 0");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ParentLocationId");

                    b.HasIndex("WarehouseId", "ParentLocationId")
                        .HasDatabaseName("IX_RII_LOCATION_WAREHOUSE_PARENT");

                    b.HasIndex("BranchCode", "WarehouseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_RII_LOCATION_BRANCH_WAREHOUSE_CODE")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("WarehouseId", "LocationType", "IsActive")
                        .HasDatabaseName("IX_RII_LOCATION_WAREHOUSE_TYPE_ACTIVE");

                    b.ToTable("RII_LOCATION", null, t =>
                        {
                            t.HasCheckConstraint("CK_RII_LOCATION_CAPACITY_QUANTITY", "[CapacityQuantity] IS NULL OR [CapacityQuantity] >= 0");

                            t.HasCheckConstraint("CK_RII_LOCATION_CAPACITY_VOLUME", "[CapacityVolume] IS NULL OR [CapacityVolume] >= 0");

                            t.HasCheckConstraint("CK_RII_LOCATION_CAPACITY_WEIGHT", "[CapacityWeight] IS NULL OR [CapacityWeight] >= 0");
                        });
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.Smtp.Domain.SmtpSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EnableSsl")
                        .HasColumnType("bit");

                    b.Property<string>("FromEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FromName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordEncrypted")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<int>("Timeout")
                        .HasColumnType("int");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("RII_SMTP_SETTING", (string)null);
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.Stock.Domain.Stock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0");

                    b.Property<short>("BusinessUnitCode")
                        .HasColumnType("smallint");

                    b.Property<string>("Code1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code4")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code5")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErpStockCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManufacturerCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("StockName")
                        .HasDatabaseName("IX_Stock_StockName");

                    b.HasIndex("BranchCode", "ErpStockCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Stock_BranchCode_ErpStockCode")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("RII_STOCK", (string)null);
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.StockMovement.Domain.StockMovementEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LineNo")
                        .HasColumnType("int");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("LotNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("OperationId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("QuantityDelta")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("StockId")
                        .HasColumnType("bigint");

                    b.Property<string>("StockStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("LocationId");

                    b.HasIndex("OperationId", "LineNo")
                        .IsUnique()
                        .HasDatabaseName("UX_RII_STOCK_MOVEMENT_OPERATION_LINE");

                    b.HasIndex("StockId", "LotNo", "SerialNo")
                        .HasDatabaseName("IX_RII_STOCK_MOVEMENT_TRACE");

                    b.HasIndex("WarehouseId", "LocationId", "OccurredAt")
                        .HasDatabaseName("IX_RII_STOCK_MOVEMENT_LOCATION_TIME");

                    b.HasIndex("StockId", "WarehouseId", "LocationId", "UnitCode", "OccurredAt")
                        .HasDatabaseName("IX_RII_STOCK_MOVEMENT_BALANCE_STREAM");

                    b.ToTable("RII_STOCK_MOVEMENT", (string)null);
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.StockMovement.Domain.StockMovementOperation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OperationCode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("ReferenceId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long?>("ReversalOfOperationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_RII_STOCK_MOVEMENT_OPERATION_IDEMPOTENCY");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OperationCode")
                        .IsUnique()
                        .HasDatabaseName("UX_RII_STOCK_MOVEMENT_OPERATION_CODE");

                    b.HasIndex("ReversalOfOperationId")
                        .IsUnique()
                        .HasDatabaseName("UX_RII_STOCK_MOVEMENT_OPERATION_REVERSAL")
                        .HasFilter("[ReversalOfOperationId] IS NOT NULL");

                    b.HasIndex("OccurredAt", "OperationType")
                        .HasDatabaseName("IX_RII_STOCK_MOVEMENT_OPERATION_OCCURRED_TYPE");

                    b.ToTable("RII_STOCK_MOVEMENT_OPERATION", (string)null);
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.SystemManagement.Domain.HangfireExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeactivatedCount")
                        .HasColumnType("int");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HangfireJobId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("InsertedCount")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("JobKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ResultSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("SourceCount")
                        .HasColumnType("int");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<int?>("UpdatedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("StartedAt");

                    b.HasIndex("JobKey", "Status");

                    b.ToTable("RII_HANGFIRE_EXECUTION_LOGS", (string)null);
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.Warehouse.Domain.Warehouse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WarehouseCode")
                        .HasColumnType("int");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("WarehouseName")
                        .HasDatabaseName("IX_Warehouse_WarehouseName");

                    b.HasIndex("BranchCode", "WarehouseCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Warehouse_BranchCode_WarehouseCode")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("RII_WAREHOUSE", (string)null);
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.YapCode.Domain.YapCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("0");

                    b.Property<string>("ConfigurableStockCode")
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<string>("ConfigurationCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DeletedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("StockId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .HasDatabaseName("IX_YapCode_Description");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("StockId")
                        .HasDatabaseName("IX_YapCode_StockId");

                    b.HasIndex("BranchCode", "ConfigurationCode")
                        .IsUnique()
                        .HasDatabaseName("IX_YapCode_BranchCode_ConfigurationCode")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("RII_YAP_CODE", (string)null);
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.AccessControl.Domain.PermissionGroupPermission", b =>
                {
                    b.HasOne("verii_wms_api_v2.Modules.AccessControl.Domain.PermissionDefinition", "PermissionDefinition")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("PermissionDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("verii_wms_api_v2.Modules.AccessControl.Domain.PermissionGroup", "PermissionGroup")
                        .WithMany("GroupPermissions")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionDefinition");

                    b.Navigation("PermissionGroup");
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.AccessControl.Domain.UserPermissionGroup", b =>
                {
                    b.HasOne("verii_wms_api_v2.Modules.AccessControl.Domain.PermissionGroup", "PermissionGroup")
                        .WithMany("UserGroups")
                        .HasForeignKey("PermissionGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("verii_wms_api_v2.Modules.Identity.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.Identity.Domain.UserDetail", b =>
                {
                    b.HasOne("verii_wms_api_v2.Modules.Identity.Domain.User", "User")
                        .WithOne("Detail")
                        .HasForeignKey("verii_wms_api_v2.Modules.Identity.Domain.UserDetail", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.Location.Domain.WarehouseLocation", b =>
                {
                    b.HasOne("verii_wms_api_v2.Modules.Location.Domain.WarehouseLocation", null)
                        .WithMany()
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("verii_wms_api_v2.Modules.Warehouse.Domain.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.StockMovement.Domain.StockMovementEntry", b =>
                {
                    b.HasOne("verii_wms_api_v2.Modules.Location.Domain.WarehouseLocation", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("verii_wms_api_v2.Modules.StockMovement.Domain.StockMovementOperation", null)
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("verii_wms_api_v2.Modules.Stock.Domain.Stock", null)
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("verii_wms_api_v2.Modules.Warehouse.Domain.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.StockMovement.Domain.StockMovementOperation", b =>
                {
                    b.HasOne("verii_wms_api_v2.Modules.StockMovement.Domain.StockMovementOperation", null)
                        .WithOne()
                        .HasForeignKey("verii_wms_api_v2.Modules.StockMovement.Domain.StockMovementOperation", "ReversalOfOperationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.YapCode.Domain.YapCode", b =>
                {
                    b.HasOne("verii_wms_api_v2.Modules.Stock.Domain.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.AccessControl.Domain.PermissionDefinition", b =>
                {
                    b.Navigation("GroupPermissions");
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.AccessControl.Domain.PermissionGroup", b =>
                {
                    b.Navigation("GroupPermissions");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("verii_wms_api_v2.Modules.Identity.Domain.User", b =>
                {
                    b.Navigation("Detail");
                });
#pragma warning restore 612, 618
        }
    }
}
