using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace verii_wms_api_v2.Migrations
{
    /// <inheritdoc />
    public partial class AddProductionAndSubcontractingTransferModules : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropCheckConstraint(
                name: "CK_RII_WT_LINE_WAREHOUSE",
                table: "RII_WT_LINE");

            migrationBuilder.DropCheckConstraint(
                name: "CK_RII_WT_HEADER_WAREHOUSE",
                table: "RII_WT_HEADER");

            migrationBuilder.AddColumn<string>(
                name: "BusinessContext",
                table: "RII_WT_HEADER",
                type: "nvarchar(40)",
                maxLength: 40,
                nullable: false,
                defaultValue: "InterWarehouse");

            migrationBuilder.CreateTable(
                name: "RII_PT_HEADER_LINK",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    WarehouseTransferHeaderId = table.Column<long>(type: "bigint", nullable: false),
                    Purpose = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false),
                    ProductionHeaderId = table.Column<long>(type: "bigint", nullable: true),
                    ProductionOrderId = table.Column<long>(type: "bigint", nullable: true),
                    ProductionOperationId = table.Column<long>(type: "bigint", nullable: true),
                    ProductionPlanNo = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ProductionOrderNo = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ProductionOperationCode = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    SourceWorkCenterCode = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    TargetWorkCenterCode = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    TriggeredByProduction = table.Column<bool>(type: "bit", nullable: false),
                    AutoGenerated = table.Column<bool>(type: "bit", nullable: false),
                    RequiredForOrderStart = table.Column<bool>(type: "bit", nullable: false),
                    RequiredForOrderCompletion = table.Column<bool>(type: "bit", nullable: false),
                    MaterialAvailabilityStatus = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false),
                    RequirementCalculatedAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: false),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_PT_HEADER_LINK", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RII_PT_HEADER_LINK_RII_WT_HEADER_WarehouseTransferHeaderId",
                        column: x => x.WarehouseTransferHeaderId,
                        principalTable: "RII_WT_HEADER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "RII_PT_POLICIES",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    PolicyKey = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false),
                    RequireProductionOrderReference = table.Column<bool>(type: "bit", nullable: false),
                    AllowManualTransfer = table.Column<bool>(type: "bit", nullable: false),
                    AllowAutomaticGeneration = table.Column<bool>(type: "bit", nullable: false),
                    CheckMaterialAvailability = table.Column<bool>(type: "bit", nullable: false),
                    BlockOnShortage = table.Column<bool>(type: "bit", nullable: false),
                    RequireTaskAssignment = table.Column<bool>(type: "bit", nullable: false),
                    RequireSourceProductionLocation = table.Column<bool>(type: "bit", nullable: false),
                    RequireTargetProductionLocation = table.Column<bool>(type: "bit", nullable: false),
                    AllowPartialSupply = table.Column<bool>(type: "bit", nullable: false),
                    AllowOverIssue = table.Column<bool>(type: "bit", nullable: false),
                    OverIssueTolerancePercent = table.Column<decimal>(type: "decimal(9,4)", precision: 9, scale: 4, nullable: false),
                    RequireApproval = table.Column<bool>(type: "bit", nullable: false),
                    RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: false),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_PT_POLICIES", x => x.Id);
                    table.CheckConstraint("CK_RII_PT_POLICY_OVER_ISSUE", "[OverIssueTolerancePercent] >= 0 AND [OverIssueTolerancePercent] <= 100");
                });

            migrationBuilder.CreateTable(
                name: "RII_ST_HEADER_LINK",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    WarehouseTransferHeaderId = table.Column<long>(type: "bigint", nullable: false),
                    Direction = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false),
                    SupplierId = table.Column<long>(type: "bigint", nullable: false),
                    SupplierCodeSnapshot = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    SupplierNameSnapshot = table.Column<string>(type: "nvarchar(300)", maxLength: 300, nullable: false),
                    SubcontractOrderNo = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    SubcontractOrderDate = table.Column<DateOnly>(type: "date", nullable: true),
                    ParentIssueTransferId = table.Column<long>(type: "bigint", nullable: true),
                    ExpectedReturnAtUtc = table.Column<DateTimeOffset>(type: "datetimeoffset", nullable: true),
                    OwnershipType = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false),
                    QualityInspectionRequired = table.Column<bool>(type: "bit", nullable: false),
                    ComponentsIssuedConfirmed = table.Column<bool>(type: "bit", nullable: false),
                    OperationCode = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    SupplierDispatchNo = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: false),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_ST_HEADER_LINK", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RII_ST_HEADER_LINK_RII_CUSTOMER_SupplierId",
                        column: x => x.SupplierId,
                        principalTable: "RII_CUSTOMER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_RII_ST_HEADER_LINK_RII_WT_HEADER_ParentIssueTransferId",
                        column: x => x.ParentIssueTransferId,
                        principalTable: "RII_WT_HEADER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_RII_ST_HEADER_LINK_RII_WT_HEADER_WarehouseTransferHeaderId",
                        column: x => x.WarehouseTransferHeaderId,
                        principalTable: "RII_WT_HEADER",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "RII_ST_POLICIES",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    PolicyKey = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false),
                    RequireSupplier = table.Column<bool>(type: "bit", nullable: false),
                    RequireSubcontractOrderForReceipt = table.Column<bool>(type: "bit", nullable: false),
                    RequireIssueBeforeReceipt = table.Column<bool>(type: "bit", nullable: false),
                    AllowOrderlessIssue = table.Column<bool>(type: "bit", nullable: false),
                    AllowOrderlessReceipt = table.Column<bool>(type: "bit", nullable: false),
                    AllowSupplierToSupplier = table.Column<bool>(type: "bit", nullable: false),
                    AllowPartialIssue = table.Column<bool>(type: "bit", nullable: false),
                    AllowPartialReceipt = table.Column<bool>(type: "bit", nullable: false),
                    RequireQualityOnReceipt = table.Column<bool>(type: "bit", nullable: false),
                    RequireTaskAssignment = table.Column<bool>(type: "bit", nullable: false),
                    RequireApproval = table.Column<bool>(type: "bit", nullable: false),
                    AllowOverReceipt = table.Column<bool>(type: "bit", nullable: false),
                    OverReceiptTolerancePercent = table.Column<decimal>(type: "decimal(9,4)", precision: 9, scale: 4, nullable: false),
                    DefaultLeadTimeDays = table.Column<int>(type: "int", nullable: false),
                    RowVersion = table.Column<byte[]>(type: "rowversion", rowVersion: true, nullable: false),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_ST_POLICIES", x => x.Id);
                    table.CheckConstraint("CK_RII_ST_POLICY_LEAD_TIME", "[DefaultLeadTimeDays] >= 0 AND [DefaultLeadTimeDays] <= 3650");
                    table.CheckConstraint("CK_RII_ST_POLICY_OVER_RECEIPT", "[OverReceiptTolerancePercent] >= 0 AND [OverReceiptTolerancePercent] <= 100");
                });

            migrationBuilder.CreateTable(
                name: "RII_PT_LINE_LINK",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ProductionTransferHeaderLinkId = table.Column<long>(type: "bigint", nullable: false),
                    WarehouseTransferLineId = table.Column<long>(type: "bigint", nullable: false),
                    LineRole = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false),
                    ProductionConsumptionId = table.Column<long>(type: "bigint", nullable: true),
                    ProductionOutputId = table.Column<long>(type: "bigint", nullable: true),
                    RequirementReference = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: true),
                    RequiredQuantity = table.Column<decimal>(type: "decimal(20,6)", precision: 20, scale: 6, nullable: false),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_PT_LINE_LINK", x => x.Id);
                    table.CheckConstraint("CK_RII_PT_LINE_LINK_REQUIRED_QTY", "[RequiredQuantity] > 0");
                    table.ForeignKey(
                        name: "FK_RII_PT_LINE_LINK_RII_PT_HEADER_LINK_ProductionTransferHeaderLinkId",
                        column: x => x.ProductionTransferHeaderLinkId,
                        principalTable: "RII_PT_HEADER_LINK",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_RII_PT_LINE_LINK_RII_WT_LINE_WarehouseTransferLineId",
                        column: x => x.WarehouseTransferLineId,
                        principalTable: "RII_WT_LINE",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "RII_ST_LINE_LINK",
                columns: table => new
                {
                    Id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    SubcontractingTransferHeaderLinkId = table.Column<long>(type: "bigint", nullable: false),
                    WarehouseTransferLineId = table.Column<long>(type: "bigint", nullable: false),
                    LineRole = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false),
                    SourceIssueLineId = table.Column<long>(type: "bigint", nullable: true),
                    ExpectedQuantity = table.Column<decimal>(type: "decimal(20,6)", precision: 20, scale: 6, nullable: false),
                    ScrapQuantity = table.Column<decimal>(type: "decimal(20,6)", precision: 20, scale: 6, nullable: false),
                    RequirementReference = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: true),
                    BranchCode = table.Column<string>(type: "nvarchar(10)", maxLength: 10, nullable: false, defaultValue: "0"),
                    CreatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    UpdatedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    DeletedDate = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false, defaultValue: false),
                    CreatedBy = table.Column<long>(type: "bigint", nullable: true),
                    UpdatedBy = table.Column<long>(type: "bigint", nullable: true),
                    DeletedBy = table.Column<long>(type: "bigint", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RII_ST_LINE_LINK", x => x.Id);
                    table.CheckConstraint("CK_RII_ST_LINE_LINK_QTY", "[ExpectedQuantity] > 0 AND [ScrapQuantity] >= 0 AND [ScrapQuantity] <= [ExpectedQuantity]");
                    table.ForeignKey(
                        name: "FK_RII_ST_LINE_LINK_RII_ST_HEADER_LINK_SubcontractingTransferHeaderLinkId",
                        column: x => x.SubcontractingTransferHeaderLinkId,
                        principalTable: "RII_ST_HEADER_LINK",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_RII_ST_LINE_LINK_RII_WT_LINE_SourceIssueLineId",
                        column: x => x.SourceIssueLineId,
                        principalTable: "RII_WT_LINE",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_RII_ST_LINE_LINK_RII_WT_LINE_WarehouseTransferLineId",
                        column: x => x.WarehouseTransferLineId,
                        principalTable: "RII_WT_LINE",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                table: "RII_PERMISSION_DEFINITIONS",
                columns: new[] { "Id", "AvailableOnMobile", "AvailableOnWeb", "BranchCode", "Code", "CreatedBy", "CreatedDate", "DeletedBy", "DeletedDate", "Description", "IsActive", "Name", "UpdatedBy", "UpdatedDate" },
                values: new object[,]
                {
                    { 2400L, false, true, "0", "WMS.PRODUCTION_TRANSFER.VIEW", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Üretim transferlerini görüntüle", null, null },
                    { 2401L, false, true, "0", "WMS.PRODUCTION_TRANSFER.CREATE", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Üretim transferi oluştur", null, null },
                    { 2402L, false, true, "0", "WMS.PRODUCTION_TRANSFER.OPERATE", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Üretim transfer operasyonunu yürüt", null, null },
                    { 2403L, false, true, "0", "WMS.PRODUCTION_TRANSFER.APPROVE", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Üretim transferini onayla", null, null },
                    { 2404L, false, true, "0", "WMS.PRODUCTION_TRANSFER.CANCEL", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Üretim transferini iptal et", null, null },
                    { 2405L, false, true, "0", "WMS.PRODUCTION_TRANSFER.SETTINGS.VIEW", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Üretim transfer ayarlarını görüntüle", null, null },
                    { 2406L, false, true, "0", "WMS.PRODUCTION_TRANSFER.SETTINGS.MANAGE", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Üretim transfer ayarlarını yönet", null, null },
                    { 2407L, false, true, "0", "WMS.PRODUCTION_TRANSFER.UPDATE", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Üretim transfer taslağını güncelle", null, null },
                    { 2408L, false, true, "0", "WMS.PRODUCTION_TRANSFER.DELETE", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Üretim transfer taslağını sil", null, null },
                    { 2410L, false, true, "0", "WMS.SUBCONTRACTING_TRANSFER.VIEW", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Fason transferlerini görüntüle", null, null },
                    { 2411L, false, true, "0", "WMS.SUBCONTRACTING_TRANSFER.CREATE", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Fason transferi oluştur", null, null },
                    { 2412L, false, true, "0", "WMS.SUBCONTRACTING_TRANSFER.OPERATE", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Fason transfer operasyonunu yürüt", null, null },
                    { 2413L, false, true, "0", "WMS.SUBCONTRACTING_TRANSFER.APPROVE", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Fason transferini onayla", null, null },
                    { 2414L, false, true, "0", "WMS.SUBCONTRACTING_TRANSFER.CANCEL", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Fason transferini iptal et", null, null },
                    { 2415L, false, true, "0", "WMS.SUBCONTRACTING_TRANSFER.SETTINGS.VIEW", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Fason transfer ayarlarını görüntüle", null, null },
                    { 2416L, false, true, "0", "WMS.SUBCONTRACTING_TRANSFER.SETTINGS.MANAGE", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Fason transfer ayarlarını yönet", null, null },
                    { 2417L, false, true, "0", "WMS.SUBCONTRACTING_TRANSFER.UPDATE", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Fason transfer taslağını güncelle", null, null },
                    { 2418L, false, true, "0", "WMS.SUBCONTRACTING_TRANSFER.DELETE", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, null, true, "Fason transfer taslağını sil", null, null }
                });

            migrationBuilder.InsertData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                columns: new[] { "Id", "BranchCode", "CreatedBy", "CreatedDate", "DeletedBy", "DeletedDate", "PermissionDefinitionId", "PermissionGroupId", "UpdatedBy", "UpdatedDate" },
                values: new object[,]
                {
                    { 2400L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2400L, 1001L, null, null },
                    { 2401L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2401L, 1001L, null, null },
                    { 2402L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2402L, 1001L, null, null },
                    { 2403L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2403L, 1001L, null, null },
                    { 2404L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2404L, 1001L, null, null },
                    { 2405L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2405L, 1001L, null, null },
                    { 2406L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2406L, 1001L, null, null },
                    { 2407L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2407L, 1001L, null, null },
                    { 2408L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2408L, 1001L, null, null },
                    { 2410L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2410L, 1001L, null, null },
                    { 2411L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2411L, 1001L, null, null },
                    { 2412L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2412L, 1001L, null, null },
                    { 2413L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2413L, 1001L, null, null },
                    { 2414L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2414L, 1001L, null, null },
                    { 2415L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2415L, 1001L, null, null },
                    { 2416L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2416L, 1001L, null, null },
                    { 2417L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2417L, 1001L, null, null },
                    { 2418L, "0", null, new DateTime(2026, 7, 21, 0, 0, 0, 0, DateTimeKind.Utc), null, null, 2418L, 1001L, null, null }
                });

            migrationBuilder.CreateIndex(
                name: "IX_RII_PT_HEADER_LINK_BranchCode_ProductionOrderNo_Purpose",
                table: "RII_PT_HEADER_LINK",
                columns: new[] { "BranchCode", "ProductionOrderNo", "Purpose" });

            migrationBuilder.CreateIndex(
                name: "IX_RII_PT_HEADER_LINK_IsDeleted",
                table: "RII_PT_HEADER_LINK",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_RII_PT_HEADER_LINK_WarehouseTransferHeaderId",
                table: "RII_PT_HEADER_LINK",
                column: "WarehouseTransferHeaderId",
                unique: true,
                filter: "[IsDeleted] = 0");

            migrationBuilder.CreateIndex(
                name: "IX_RII_PT_LINE_LINK_IsDeleted",
                table: "RII_PT_LINE_LINK",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_RII_PT_LINE_LINK_ProductionTransferHeaderLinkId",
                table: "RII_PT_LINE_LINK",
                column: "ProductionTransferHeaderLinkId");

            migrationBuilder.CreateIndex(
                name: "IX_RII_PT_LINE_LINK_WarehouseTransferLineId",
                table: "RII_PT_LINE_LINK",
                column: "WarehouseTransferLineId",
                unique: true,
                filter: "[IsDeleted] = 0");

            migrationBuilder.CreateIndex(
                name: "IX_RII_PT_POLICIES_BranchCode_PolicyKey",
                table: "RII_PT_POLICIES",
                columns: new[] { "BranchCode", "PolicyKey" },
                unique: true,
                filter: "[IsDeleted] = 0");

            migrationBuilder.CreateIndex(
                name: "IX_RII_PT_POLICIES_IsDeleted",
                table: "RII_PT_POLICIES",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_RII_ST_HEADER_LINK_BranchCode_SubcontractOrderNo_Direction",
                table: "RII_ST_HEADER_LINK",
                columns: new[] { "BranchCode", "SubcontractOrderNo", "Direction" });

            migrationBuilder.CreateIndex(
                name: "IX_RII_ST_HEADER_LINK_BranchCode_SupplierId_Direction_ExpectedReturnAtUtc",
                table: "RII_ST_HEADER_LINK",
                columns: new[] { "BranchCode", "SupplierId", "Direction", "ExpectedReturnAtUtc" });

            migrationBuilder.CreateIndex(
                name: "IX_RII_ST_HEADER_LINK_IsDeleted",
                table: "RII_ST_HEADER_LINK",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_RII_ST_HEADER_LINK_ParentIssueTransferId",
                table: "RII_ST_HEADER_LINK",
                column: "ParentIssueTransferId");

            migrationBuilder.CreateIndex(
                name: "IX_RII_ST_HEADER_LINK_SupplierId",
                table: "RII_ST_HEADER_LINK",
                column: "SupplierId");

            migrationBuilder.CreateIndex(
                name: "IX_RII_ST_HEADER_LINK_WarehouseTransferHeaderId",
                table: "RII_ST_HEADER_LINK",
                column: "WarehouseTransferHeaderId",
                unique: true,
                filter: "[IsDeleted] = 0");

            migrationBuilder.CreateIndex(
                name: "IX_RII_ST_LINE_LINK_IsDeleted",
                table: "RII_ST_LINE_LINK",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_RII_ST_LINE_LINK_SourceIssueLineId",
                table: "RII_ST_LINE_LINK",
                column: "SourceIssueLineId");

            migrationBuilder.CreateIndex(
                name: "IX_RII_ST_LINE_LINK_SubcontractingTransferHeaderLinkId",
                table: "RII_ST_LINE_LINK",
                column: "SubcontractingTransferHeaderLinkId");

            migrationBuilder.CreateIndex(
                name: "IX_RII_ST_LINE_LINK_WarehouseTransferLineId",
                table: "RII_ST_LINE_LINK",
                column: "WarehouseTransferLineId",
                unique: true,
                filter: "[IsDeleted] = 0");

            migrationBuilder.CreateIndex(
                name: "IX_RII_ST_POLICIES_BranchCode_PolicyKey",
                table: "RII_ST_POLICIES",
                columns: new[] { "BranchCode", "PolicyKey" },
                unique: true,
                filter: "[IsDeleted] = 0");

            migrationBuilder.CreateIndex(
                name: "IX_RII_ST_POLICIES_IsDeleted",
                table: "RII_ST_POLICIES",
                column: "IsDeleted");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "RII_PT_LINE_LINK");

            migrationBuilder.DropTable(
                name: "RII_PT_POLICIES");

            migrationBuilder.DropTable(
                name: "RII_ST_LINE_LINK");

            migrationBuilder.DropTable(
                name: "RII_ST_POLICIES");

            migrationBuilder.DropTable(
                name: "RII_PT_HEADER_LINK");

            migrationBuilder.DropTable(
                name: "RII_ST_HEADER_LINK");

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2400L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2401L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2402L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2403L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2404L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2405L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2406L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2407L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2408L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2410L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2411L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2412L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2413L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2414L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2415L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2416L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2417L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_GROUP_PERMISSIONS",
                keyColumn: "Id",
                keyValue: 2418L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2400L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2401L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2402L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2403L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2404L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2405L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2406L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2407L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2408L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2410L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2411L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2412L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2413L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2414L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2415L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2416L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2417L);

            migrationBuilder.DeleteData(
                table: "RII_PERMISSION_DEFINITIONS",
                keyColumn: "Id",
                keyValue: 2418L);

            migrationBuilder.DropColumn(
                name: "BusinessContext",
                table: "RII_WT_HEADER");

            migrationBuilder.AddCheckConstraint(
                name: "CK_RII_WT_LINE_WAREHOUSE",
                table: "RII_WT_LINE",
                sql: "[SourceWarehouseId] <> [TargetWarehouseId]");

            migrationBuilder.AddCheckConstraint(
                name: "CK_RII_WT_HEADER_WAREHOUSE",
                table: "RII_WT_HEADER",
                sql: "[SourceWarehouseId] <> [TargetWarehouseId]");
        }
    }
}
