using verii_wms_api_v2.Modules.Production.Domain;
using verii_wms_api_v2.Modules.WarehouseTransfer.Domain;
using verii_wms_api_v2.Shared.Domain;

namespace verii_wms_api_v2.Modules.ProductionTransfer.Domain;

public enum ProductionTransferPurpose
{
    MaterialSupply = 1,
    WorkInProgressMove = 2,
    OutputMove = 3
}

public enum ProductionTransferLineRole
{
    ConsumptionSupply = 1,
    WorkInProgress = 2,
    ProductionOutput = 3,
    ReturnToWarehouse = 4
}

public enum ProductionMaterialAvailabilityStatus
{
    NotChecked = 1,
    Available = 2,
    PartiallyAvailable = 3,
    Shortage = 4
}

public enum ProductionTransferWorkflowStatus
{
    Planned = 1,
    Picking = 2,
    AwaitingHandover = 3,
    Completed = 4,
    CompletedWithShortage = 5,
    Cancelled = 6
}

public sealed class ProductionTransferHeaderLink : BaseEntity
{
    public long WarehouseTransferHeaderId { get; set; }
    public WarehouseTransferHeader WarehouseTransferHeader { get; set; } = null!;
    public ProductionTransferPurpose Purpose { get; set; }
    public long? ProductionHeaderId { get; set; }
    public ProductionHeader? ProductionHeader { get; set; }
    public long? ProductionOrderId { get; set; }
    public ProductionOrder? ProductionOrder { get; set; }
    public long? ProductionOperationId { get; set; }
    public string? ProductionPlanNo { get; set; }
    public string? ProductionOrderNo { get; set; }
    public string? ProductionOperationCode { get; set; }
    public string? SourceWorkCenterCode { get; set; }
    public string? TargetWorkCenterCode { get; set; }
    public bool TriggeredByProduction { get; set; }
    public bool AutoGenerated { get; set; }
    public bool RequiredForOrderStart { get; set; }
    public bool RequiredForOrderCompletion { get; set; }
    public ProductionMaterialAvailabilityStatus MaterialAvailabilityStatus { get; set; } = ProductionMaterialAvailabilityStatus.NotChecked;
    public DateTimeOffset? RequirementCalculatedAtUtc { get; set; }
    public ProductionTransferWorkflowStatus WorkflowStatus { get; set; } = ProductionTransferWorkflowStatus.Planned;
    public long? RequestedByUserId { get; set; }
    public string? RequestedByNameSnapshot { get; set; }
    public long? HandoverConfirmedBy { get; set; }
    public DateTimeOffset? HandoverConfirmedAtUtc { get; set; }
    public string? HandoverShortageReason { get; set; }
    public Guid? LastPickingCompletionIdempotencyKey { get; set; }
    public Guid? LastHandoverIdempotencyKey { get; set; }
    public long? ParentWarehouseTransferHeaderId { get; set; }
    public long? ResidualWarehouseTransferHeaderId { get; set; }
    public byte[] RowVersion { get; set; } = [];
    public ICollection<ProductionTransferLineLink> Lines { get; set; } = [];
}

public sealed class ProductionTransferLineLink : BaseEntity
{
    public long ProductionTransferHeaderLinkId { get; set; }
    public ProductionTransferHeaderLink HeaderLink { get; set; } = null!;
    public long WarehouseTransferLineId { get; set; }
    public WarehouseTransferLine WarehouseTransferLine { get; set; } = null!;
    public ProductionTransferLineRole LineRole { get; set; }
    public long? ProductionConsumptionId { get; set; }
    public ProductionMaterialRequirement? ProductionConsumption { get; set; }
    public long? ProductionOutputId { get; set; }
    public ProductionOutputExpectation? ProductionOutput { get; set; }
    public string? RequirementReference { get; set; }
    public decimal RequiredQuantity { get; set; }
    public decimal HandedOverQuantity { get; set; }
    public decimal ShortClosedQuantity { get; set; }
}

/// <summary>
/// Accepted physical barcode scans for a production transfer. This is an append-only
/// operational journal used for idempotency, label-capacity control and traceability.
/// </summary>
public sealed class ProductionTransferBarcodeScan : BaseEntity
{
    public long ProductionTransferHeaderLinkId { get; set; }
    public ProductionTransferHeaderLink HeaderLink { get; set; } = null!;
    public long ProductionTransferLineLinkId { get; set; }
    public ProductionTransferLineLink LineLink { get; set; } = null!;
    public Guid IdempotencyKey { get; set; }
    public string BarcodeValue { get; set; } = string.Empty;
    public string NormalizedBarcode { get; set; } = string.Empty;
    public string BarcodeSource { get; set; } = string.Empty;
    public long StockId { get; set; }
    public long? YapCodeId { get; set; }
    public string UnitCode { get; set; } = string.Empty;
    public string? LotNo { get; set; }
    public string? SerialNo { get; set; }
    public decimal Quantity { get; set; }
    public long SourceLocationId { get; set; }
    public long TargetLocationId { get; set; }
    public DateTimeOffset ScannedAtUtc { get; set; }
}

public sealed class ProductionTransferPolicy : BaseEntity
{
    public string PolicyKey { get; set; } = "DEFAULT";
    public ProductionOrderSourceType ProductionOrderSource { get; set; } = ProductionOrderSourceType.NetsisErpFunctions;
    public string WmsSourceSystemCode { get; set; } = "WINDBOX";
    public bool RequireProductionOrderReference { get; set; } = true;
    public bool AllowManualTransfer { get; set; } = true;
    public bool RequireErpMasterDataForManualTransfer { get; set; } = true;
    public bool AllowAutomaticGeneration { get; set; } = true;
    public bool CheckMaterialAvailability { get; set; } = true;
    public bool BlockOnShortage { get; set; } = true;
    public bool RequireTaskAssignment { get; set; } = true;
    public bool RequireSourceProductionLocation { get; set; } = true;
    public bool RequireTargetProductionLocation { get; set; } = true;
    public bool AllowPartialSupply { get; set; } = true;
    public bool AllowOverIssue { get; set; }
    public decimal OverIssueTolerancePercent { get; set; }
    public bool RequireApproval { get; set; }
    public WarehouseTransferCancellationReturnPolicy CancellationReturnPolicy { get; set; } = WarehouseTransferCancellationReturnPolicy.OriginalSourceLocation;
    public byte[] RowVersion { get; set; } = [];
}
