using verii_wms_api_v2.Modules.Production.Domain;
using verii_wms_api_v2.Modules.ProductionTransfer.Domain;
using verii_wms_api_v2.Modules.WarehouseTransfer.Application;
using verii_wms_api_v2.Modules.WarehouseTransfer.Domain;
using verii_wms_api_v2.Shared;

namespace verii_wms_api_v2.Modules.ProductionTransfer.Application;

public sealed record ProductionTransferLineContextRequest(
    int LineIndex,
    ProductionTransferLineRole LineRole,
    long? ProductionConsumptionId,
    long? ProductionOutputId,
    string? RequirementReference,
    decimal RequiredQuantity);

public sealed record CreateProductionTransferDraftRequest(
    CreateWarehouseTransferDraftRequest Transfer,
    ProductionTransferPurpose Purpose,
    long? ProductionHeaderId,
    long? ProductionOrderId,
    long? ProductionOperationId,
    string? ProductionPlanNo,
    string? ProductionOrderNo,
    string? ProductionOperationCode,
    string? SourceWorkCenterCode,
    string? TargetWorkCenterCode,
    bool TriggeredByProduction,
    bool AutoGenerated,
    bool RequiredForOrderStart,
    bool RequiredForOrderCompletion,
    IReadOnlyList<ProductionTransferLineContextRequest>? LineContexts);

public sealed record ProductionTransferContextDto(
    long LinkId,
    ProductionTransferPurpose Purpose,
    long? ProductionHeaderId,
    long? ProductionOrderId,
    long? ProductionOperationId,
    string? ProductionPlanNo,
    string? ProductionOrderNo,
    string? ProductionOperationCode,
    string? SourceWorkCenterCode,
    string? TargetWorkCenterCode,
    bool TriggeredByProduction,
    bool AutoGenerated,
    bool RequiredForOrderStart,
    bool RequiredForOrderCompletion,
    ProductionMaterialAvailabilityStatus MaterialAvailabilityStatus);

public sealed record ProductionTransferDetail(WarehouseTransferDetail Transfer,ProductionTransferContextDto Context);

public sealed record ProductionTransferPolicyDto(
    long Id,string BranchCode,string RowVersion,ProductionOrderSourceType ProductionOrderSource,string WmsSourceSystemCode,
    bool RequireProductionOrderReference,bool AllowManualTransfer,bool RequireErpMasterDataForManualTransfer,bool AllowAutomaticGeneration,
    bool CheckMaterialAvailability,bool BlockOnShortage,bool RequireTaskAssignment,bool RequireSourceProductionLocation,
    bool RequireTargetProductionLocation,bool AllowPartialSupply,bool AllowOverIssue,decimal OverIssueTolerancePercent,
    bool RequireApproval,WarehouseTransferCancellationReturnPolicy CancellationReturnPolicy,long? UpdatedBy,DateTime? UpdatedDate);

public sealed record UpdateProductionTransferPolicyRequest(
    string BranchCode,string? RowVersion,ProductionOrderSourceType ProductionOrderSource,string WmsSourceSystemCode,
    bool RequireProductionOrderReference,bool AllowManualTransfer,bool RequireErpMasterDataForManualTransfer,bool AllowAutomaticGeneration,
    bool CheckMaterialAvailability,bool BlockOnShortage,bool RequireTaskAssignment,bool RequireSourceProductionLocation,
    bool RequireTargetProductionLocation,bool AllowPartialSupply,bool AllowOverIssue,decimal OverIssueTolerancePercent,
    bool RequireApproval,WarehouseTransferCancellationReturnPolicy CancellationReturnPolicy);

public interface IProductionTransferService
{
    Task<CreateWarehouseTransferDraftResult> CreateDraftAsync(CreateProductionTransferDraftRequest request,long actor,CancellationToken ct=default);
    Task<PagedResponse<WarehouseTransferGridRow>> GetPagedAsync(PagedRequest request,CancellationToken ct=default);
    Task<ProductionTransferDetail> GetDetailAsync(long id,CancellationToken ct=default);
    Task<ProductionTransferDetail> UpdateDraftAsync(long id,UpdateWarehouseTransferDraftRequest request,long actor,CancellationToken ct=default);
    Task DeleteDraftAsync(long id,long actor,CancellationToken ct=default);
    Task<ProductionTransferPolicyDto> GetPolicyAsync(string branchCode,CancellationToken ct=default);
    Task<ProductionTransferPolicyDto> UpdatePolicyAsync(UpdateProductionTransferPolicyRequest request,long actor,CancellationToken ct=default);
}
