using System.Data;
using Microsoft.EntityFrameworkCore;
using verii_wms_api_v2.Modules.Audit.Application;
using verii_wms_api_v2.Modules.Production.Domain;
using verii_wms_api_v2.Modules.ProductionTransfer.Domain;
using verii_wms_api_v2.Modules.StockBalance.Domain;
using verii_wms_api_v2.Modules.WarehouseTransfer.Application;
using verii_wms_api_v2.Modules.WarehouseTransfer.Domain;
using verii_wms_api_v2.Shared;
using verii_wms_api_v2.Shared.Application.Abstractions.Persistence;
using verii_wms_api_v2.Shared.Application.Exceptions;

namespace verii_wms_api_v2.Modules.ProductionTransfer.Application;

public sealed class ProductionTransferService(
    IUnitOfWork uow,
    IWarehouseTransferService transfers,
    IAuditLogWriter audit) : IProductionTransferService
{
    private static readonly WarehouseTransferBusinessContext[] Contexts =
    [
        WarehouseTransferBusinessContext.ProductionMaterialSupply,
        WarehouseTransferBusinessContext.ProductionWipMove,
        WarehouseTransferBusinessContext.ProductionOutputMove
    ];

    private IGenericRepository<ProductionTransferHeaderLink> Links => uow.Repository<ProductionTransferHeaderLink>();
    private IGenericRepository<ProductionTransferPolicy> Policies => uow.Repository<ProductionTransferPolicy>();

    public Task<CreateWarehouseTransferDraftResult> CreateDraftAsync(
        CreateProductionTransferDraftRequest request,long actor,CancellationToken ct=default)
    {
        Validate(request);
        return uow.ExecuteInTransactionAsync(async token =>
        {
            var existing=await uow.Repository<WarehouseTransferHeader>().Query()
                .Where(x=>x.CorrelationId==request.Transfer.IdempotencyKey)
                .Select(x=>new{x.Id,x.BusinessContext}).SingleOrDefaultAsync(token);
            if(existing is not null)
            {
                if(!Contexts.Contains(existing.BusinessContext))
                    throw AppException.Conflict("Aynı idempotency anahtarı başka bir transfer bağlamında kullanılmış.");
                var replay=await transfers.CreateDraftAsync(request.Transfer with{BusinessContext=existing.BusinessContext},actor,token);
                if(!await Links.AnyAsync(x=>x.WarehouseTransferHeaderId==existing.Id,token))
                    throw AppException.Conflict("Üretim transferi önceki istekte eksik bağlamla oluşmuş; teknik inceleme gereklidir.");
                return replay;
            }

            var policy=await GetPolicyEntityAsync(request.Transfer.BranchCode,token);
            ValidatePolicy(request,policy);
            await ValidateProductionReferencesAsync(request,token);
            var context=Context(request.Purpose);
            var availability=policy.CheckMaterialAvailability
                ? await AvailabilityAsync(request.Transfer,token)
                : ProductionMaterialAvailabilityStatus.NotChecked;
            if(policy.BlockOnShortage&&availability==ProductionMaterialAvailabilityStatus.Shortage)
                throw AppException.Conflict("Üretim besleme transferi için kaynak rafta yeterli kullanılabilir stok yok.");

            var result=await transfers.CreateDraftAsync(request.Transfer with{BusinessContext=context},actor,token);
            var header=await uow.Repository<WarehouseTransferHeader>().Query(true)
                .Include(x=>x.Lines).SingleAsync(x=>x.Id==result.Id,token);
            header.RequireApproval|=policy.RequireApproval;
            header.CancellationReturnPolicy=policy.CancellationReturnPolicy;
            if(header.RequireApproval&&header.ApprovalStatus==Modules.WarehouseOperations.Domain.OperationApprovalStatus.NotRequired)
                header.ApprovalStatus=Modules.WarehouseOperations.Domain.OperationApprovalStatus.Pending;

            var now=DateTime.UtcNow;
            var link=new ProductionTransferHeaderLink{
                BranchCode=header.BranchCode,CreatedBy=actor,CreatedDate=now,WarehouseTransferHeader=header,
                Purpose=request.Purpose,ProductionHeaderId=request.ProductionHeaderId,ProductionOrderId=request.ProductionOrderId,
                ProductionOperationId=request.ProductionOperationId,ProductionPlanNo=Clean(request.ProductionPlanNo,100),
                ProductionOrderNo=Clean(request.ProductionOrderNo,100),ProductionOperationCode=Clean(request.ProductionOperationCode,100),
                SourceWorkCenterCode=Clean(request.SourceWorkCenterCode,100),TargetWorkCenterCode=Clean(request.TargetWorkCenterCode,100),
                TriggeredByProduction=request.TriggeredByProduction,AutoGenerated=request.AutoGenerated,
                RequiredForOrderStart=request.RequiredForOrderStart,RequiredForOrderCompletion=request.RequiredForOrderCompletion,
                MaterialAvailabilityStatus=availability,RequirementCalculatedAtUtc=policy.CheckMaterialAvailability?DateTimeOffset.UtcNow:null
            };
            var contexts=(request.LineContexts??[]).ToDictionary(x=>x.LineIndex);
            foreach(var line in header.Lines.OrderBy(x=>x.LineNo))
            {
                contexts.TryGetValue(line.LineNo-1,out var lineContext);
                link.Lines.Add(new ProductionTransferLineLink{
                    BranchCode=header.BranchCode,CreatedBy=actor,CreatedDate=now,WarehouseTransferLine=line,
                    LineRole=lineContext?.LineRole??DefaultRole(request.Purpose),
                    ProductionConsumptionId=lineContext?.ProductionConsumptionId,
                    ProductionOutputId=lineContext?.ProductionOutputId,
                    RequirementReference=Clean(lineContext?.RequirementReference,150),
                    RequiredQuantity=lineContext?.RequiredQuantity??line.RequestedQuantity
                });
            }
            await Links.AddAsync(link,token);
            await uow.SaveChangesAsync(token);
            await audit.WriteAsync(new("production-transfer.draft.create",nameof(ProductionTransferHeaderLink),link.Id.ToString(),
                "Succeeded","production-transfer",NewValues:new{result.Id,result.DocumentNo,request.Purpose,request.ProductionOrderNo,availability},
                ChangedFields:["Transfer","ProductionContext","LineLinks"]),token);
            return result;
        },ct,IsolationLevel.Serializable);
    }

    public Task<PagedResponse<WarehouseTransferGridRow>> GetPagedAsync(PagedRequest request,CancellationToken ct=default) =>
        transfers.GetPagedByContextAsync(request,Contexts,ct);

    public async Task<ProductionTransferDetail> GetDetailAsync(long id,CancellationToken ct=default)
    {
        var transfer=await transfers.GetDetailForContextAsync(id,Contexts,ct);
        var context=await Links.Query().Where(x=>x.WarehouseTransferHeaderId==id)
            .Select(x=>new ProductionTransferContextDto(x.Id,x.Purpose,x.ProductionHeaderId,x.ProductionOrderId,
                x.ProductionOperationId,x.ProductionPlanNo,x.ProductionOrderNo,x.ProductionOperationCode,
                x.SourceWorkCenterCode,x.TargetWorkCenterCode,x.TriggeredByProduction,x.AutoGenerated,
                x.RequiredForOrderStart,x.RequiredForOrderCompletion,x.MaterialAvailabilityStatus))
            .SingleOrDefaultAsync(ct)??throw AppException.NotFound("Üretim transfer bağlamı bulunamadı.");
        return new(transfer,context);
    }

    public async Task<ProductionTransferDetail> UpdateDraftAsync(
        long id,UpdateWarehouseTransferDraftRequest request,long actor,CancellationToken ct=default)
    {
        await transfers.EnsureContextAsync(id,Contexts,ct);
        await transfers.UpdateDraftAsync(id,request,actor,ct);
        return await GetDetailAsync(id,ct);
    }

    public Task DeleteDraftAsync(long id,long actor,CancellationToken ct=default)=>
        uow.ExecuteInTransactionAsync(async token=>{
            await transfers.EnsureContextAsync(id,Contexts,token);
            var link=await Links.Query(true).SingleOrDefaultAsync(x=>x.WarehouseTransferHeaderId==id,token)
                ??throw AppException.NotFound("Üretim transfer bağlamı bulunamadı.");
            var now=DateTime.UtcNow;
            await uow.Repository<ProductionTransferLineLink>().Query(true).Where(x=>x.ProductionTransferHeaderLinkId==link.Id)
                .ExecuteUpdateAsync(x=>x.SetProperty(v=>v.IsDeleted,true).SetProperty(v=>v.DeletedBy,actor).SetProperty(v=>v.DeletedDate,now),token);
            link.IsDeleted=true;link.DeletedBy=actor;link.DeletedDate=now;
            await uow.SaveChangesAsync(token);
            await transfers.DeleteDraftAsync(id,actor,token);
            return true;
        },ct);

    public async Task<ProductionTransferPolicyDto> GetPolicyAsync(string branchCode,CancellationToken ct=default) =>
        Map(await GetPolicyEntityAsync(branchCode,ct));

    public async Task<ProductionTransferPolicyDto> UpdatePolicyAsync(
        UpdateProductionTransferPolicyRequest request,long actor,CancellationToken ct=default)
    {
        if(request.OverIssueTolerancePercent is <0 or >100)
            throw AppException.BadRequest("Fazla sarf toleransı 0-100 arasında olmalıdır.");
        if(!request.AllowOverIssue&&request.OverIssueTolerancePercent!=0)
            throw AppException.BadRequest("Fazla sarf kapalıyken tolerans sıfır olmalıdır.");
        var branch=Branch(request.BranchCode);
        var entity=await Policies.FirstOrDefaultAsync(x=>x.BranchCode==branch&&x.PolicyKey=="DEFAULT",true,ct);
        var before=entity is null?null:Map(entity);
        if(entity is null){entity=Default(branch);entity.CreatedBy=actor;await Policies.AddAsync(entity,ct);}
        else EnsureRowVersion(entity.RowVersion,request.RowVersion);
        entity.RequireProductionOrderReference=request.RequireProductionOrderReference;
        entity.AllowManualTransfer=request.AllowManualTransfer;entity.AllowAutomaticGeneration=request.AllowAutomaticGeneration;
        entity.CheckMaterialAvailability=request.CheckMaterialAvailability;entity.BlockOnShortage=request.BlockOnShortage;
        entity.RequireTaskAssignment=request.RequireTaskAssignment;
        entity.RequireSourceProductionLocation=request.RequireSourceProductionLocation;
        entity.RequireTargetProductionLocation=request.RequireTargetProductionLocation;
        entity.AllowPartialSupply=request.AllowPartialSupply;entity.AllowOverIssue=request.AllowOverIssue;
        entity.OverIssueTolerancePercent=request.OverIssueTolerancePercent;entity.RequireApproval=request.RequireApproval;
        entity.CancellationReturnPolicy=request.CancellationReturnPolicy;
        entity.UpdatedBy=actor;entity.UpdatedDate=DateTime.UtcNow;
        try{await uow.SaveChangesAsync(ct);}
        catch(DbUpdateConcurrencyException){throw AppException.Conflict("Üretim transfer politikası başka bir kullanıcı tarafından değiştirildi. Sayfayı yenileyin.");}
        var result=Map(entity);
        await audit.WriteAsync(new("production-transfer.policy.update",nameof(ProductionTransferPolicy),entity.Id.ToString(),
            "Succeeded","production-transfer",OldValues:before,NewValues:result,ChangedFields:["Policy"]),ct);
        return result;
    }

    private async Task<ProductionMaterialAvailabilityStatus> AvailabilityAsync(
        CreateWarehouseTransferDraftRequest request,CancellationToken ct)
    {
        var balances=uow.Repository<LocationStockBalance>().Query();
        var availableCount=0;
        foreach(var line in request.Lines)
        {
            var available=await balances.Where(x=>x.WarehouseId==request.SourceWarehouseId
                    && x.LocationId==line.DefaultSourceLocationId && x.StockId==line.StockId
                    && x.YapCodeId==line.YapCodeId && x.StockStatus=="Available")
                .SumAsync(x=>(decimal?)x.AvailableQuantity,ct)??0;
            if(available>=line.Quantity)availableCount++;
        }
        if(availableCount==request.Lines.Count)return ProductionMaterialAvailabilityStatus.Available;
        return availableCount==0?ProductionMaterialAvailabilityStatus.Shortage:ProductionMaterialAvailabilityStatus.PartiallyAvailable;
    }

    private async Task<ProductionTransferPolicy> GetPolicyEntityAsync(string branchCode,CancellationToken ct)
    {
        var branch=Branch(branchCode);
        return await Policies.FirstOrDefaultAsync(x=>x.BranchCode==branch&&x.PolicyKey=="DEFAULT",false,ct)??Default(branch);
    }

    private async Task ValidateProductionReferencesAsync(
        CreateProductionTransferDraftRequest request,
        CancellationToken ct)
    {
        var branch=Branch(request.Transfer.BranchCode);
        if(request.ProductionHeaderId.HasValue)
        {
            var exists=await uow.Repository<ProductionHeader>().Query()
                .AnyAsync(x=>x.Id==request.ProductionHeaderId&&x.BranchCode==branch,ct);
            if(!exists)throw AppException.BadRequest("Bağlı üretim planı bulunamadı.");
        }
        if(request.ProductionOrderId.HasValue)
        {
            var order=await uow.Repository<ProductionOrder>().Query()
                .Where(x=>x.Id==request.ProductionOrderId&&x.BranchCode==branch)
                .Select(x=>new{x.Id,x.ProductionHeaderId}).SingleOrDefaultAsync(ct)
                ??throw AppException.BadRequest("Bağlı üretim emri bulunamadı.");
            if(request.ProductionHeaderId.HasValue&&order.ProductionHeaderId!=request.ProductionHeaderId)
                throw AppException.BadRequest("Üretim emri seçilen üretim planına ait değil.");
        }
        var consumptionIds=(request.LineContexts??[]).Where(x=>x.ProductionConsumptionId.HasValue)
            .Select(x=>x.ProductionConsumptionId!.Value).Distinct().ToArray();
        if(consumptionIds.Length>0)
        {
            var count=await uow.Repository<ProductionMaterialRequirement>().Query()
                .CountAsync(x=>consumptionIds.Contains(x.Id)&&
                    (!request.ProductionOrderId.HasValue||x.ProductionOrderId==request.ProductionOrderId),ct);
            if(count!=consumptionIds.Length)
                throw AppException.BadRequest("Üretim transferindeki malzeme ihtiyaç bağlantılarından biri geçersiz.");
        }
        var outputIds=(request.LineContexts??[]).Where(x=>x.ProductionOutputId.HasValue)
            .Select(x=>x.ProductionOutputId!.Value).Distinct().ToArray();
        if(outputIds.Length>0)
        {
            var count=await uow.Repository<ProductionOutputExpectation>().Query()
                .CountAsync(x=>outputIds.Contains(x.Id)&&
                    (!request.ProductionOrderId.HasValue||x.ProductionOrderId==request.ProductionOrderId),ct);
            if(count!=outputIds.Length)
                throw AppException.BadRequest("Üretim transferindeki çıktı bağlantılarından biri geçersiz.");
        }
    }

    private static void Validate(CreateProductionTransferDraftRequest request)
    {
        if(request.Transfer is null)throw AppException.BadRequest("Transfer gövdesi zorunludur.");
        if(request.LineContexts?.Any(x=>x.LineIndex<0||x.LineIndex>=request.Transfer.Lines.Count||x.RequiredQuantity<=0)==true)
            throw AppException.BadRequest("Üretim transfer kalem bağlamı geçersiz.");
        if(request.LineContexts?.GroupBy(x=>x.LineIndex).Any(x=>x.Count()>1)==true)
            throw AppException.BadRequest("Aynı transfer kalemine birden fazla üretim bağlamı atanamaz.");
    }

    private static void ValidatePolicy(CreateProductionTransferDraftRequest request,ProductionTransferPolicy policy)
    {
        if(policy.RequireProductionOrderReference&&string.IsNullOrWhiteSpace(request.ProductionOrderNo)&&!request.ProductionOrderId.HasValue)
            throw AppException.BadRequest("Üretim emri referansı zorunludur.");
        if(!policy.AllowManualTransfer&&!request.TriggeredByProduction)
            throw AppException.BadRequest("Manuel üretim transferi politikada kapalıdır.");
        if(!policy.AllowAutomaticGeneration&&request.AutoGenerated)
            throw AppException.BadRequest("Otomatik üretim transferi politikada kapalıdır.");
        var taskBased=request.Transfer.InitiationMode is WarehouseTransferInitiationMode.OrderBasedTask or WarehouseTransferInitiationMode.StockBasedTask;
        if(policy.RequireTaskAssignment&&!taskBased)
            throw AppException.BadRequest("Üretime transferde emirli yürütme zorunludur. Kullanıcı transfer oluşturulduktan sonra atanabilir.");
        if(policy.RequireSourceProductionLocation&&request.Transfer.Lines.Any(x=>!x.DefaultSourceLocationId.HasValue))
            throw AppException.BadRequest("Üretime transferde kaynak raf zorunludur.");
        if(policy.RequireTargetProductionLocation&&request.Transfer.Lines.Any(x=>!x.DefaultTargetLocationId.HasValue))
            throw AppException.BadRequest("Üretime transferde üretim besleme/hedef rafı zorunludur.");
        if(!policy.AllowPartialSupply&&request.LineContexts?.Any(x=>
               request.Transfer.Lines[x.LineIndex].Quantity<x.RequiredQuantity)==true)
            throw AppException.BadRequest("Kısmi üretim beslemesi politikada kapalıdır.");
        if(!policy.AllowOverIssue&&request.LineContexts?.Any(x=>x.RequiredQuantity>0&&request.Transfer.Lines[x.LineIndex].Quantity>x.RequiredQuantity)==true)
            throw AppException.BadRequest("Talep miktarından fazla üretim transferi politikada kapalıdır.");
        if(policy.AllowOverIssue&&request.LineContexts?.Any(x=>x.RequiredQuantity>0
               && request.Transfer.Lines[x.LineIndex].Quantity>x.RequiredQuantity*(1+policy.OverIssueTolerancePercent/100m))==true)
            throw AppException.BadRequest("Üretim transfer miktarı fazla sarf toleransını aşıyor.");
    }

    private static WarehouseTransferBusinessContext Context(ProductionTransferPurpose purpose)=>purpose switch{
        ProductionTransferPurpose.MaterialSupply=>WarehouseTransferBusinessContext.ProductionMaterialSupply,
        ProductionTransferPurpose.WorkInProgressMove=>WarehouseTransferBusinessContext.ProductionWipMove,
        ProductionTransferPurpose.OutputMove=>WarehouseTransferBusinessContext.ProductionOutputMove,
        _=>throw AppException.BadRequest("Üretim transfer amacı geçersiz.")
    };
    private static ProductionTransferLineRole DefaultRole(ProductionTransferPurpose purpose)=>purpose switch{
        ProductionTransferPurpose.MaterialSupply=>ProductionTransferLineRole.ConsumptionSupply,
        ProductionTransferPurpose.WorkInProgressMove=>ProductionTransferLineRole.WorkInProgress,
        _=>ProductionTransferLineRole.ProductionOutput
    };
    private static ProductionTransferPolicy Default(string branch)=>new(){BranchCode=branch,PolicyKey="DEFAULT",CreatedDate=DateTime.UtcNow};
    private static ProductionTransferPolicyDto Map(ProductionTransferPolicy x)=>new(x.Id,x.BranchCode,Convert.ToBase64String(x.RowVersion),x.RequireProductionOrderReference,
        x.AllowManualTransfer,x.AllowAutomaticGeneration,x.CheckMaterialAvailability,x.BlockOnShortage,x.RequireTaskAssignment,
        x.RequireSourceProductionLocation,x.RequireTargetProductionLocation,x.AllowPartialSupply,x.AllowOverIssue,
        x.OverIssueTolerancePercent,x.RequireApproval,x.CancellationReturnPolicy,x.UpdatedBy,x.UpdatedDate);
    private static void EnsureRowVersion(byte[] current,string? supplied){
        byte[] expected;try{expected=Convert.FromBase64String(supplied??string.Empty);}
        catch(FormatException){throw AppException.BadRequest("Geçersiz eşzamanlılık anahtarı.");}
        if(!System.Security.Cryptography.CryptographicOperations.FixedTimeEquals(current,expected))
            throw AppException.Conflict("Üretim transfer politikası başka bir kullanıcı tarafından değiştirildi. Sayfayı yenileyin.");
    }
    private static string Branch(string? value)=>string.IsNullOrWhiteSpace(value)?"0":value.Trim();
    private static string? Clean(string? value,int max){var result=value?.Trim();return string.IsNullOrEmpty(result)?null:result.Length<=max?result:result[..max];}
}
