using System.Globalization;
using verii_wms_api_v2.Modules.ProductionTransfer.Domain;
using verii_wms_api_v2.Modules.WarehouseTransfer.Domain;

namespace verii_wms_api_v2.Modules.ProductionTransfer.Application;

public enum ProductionWorkOrderTransferTab
{
    Picking = 1,
    Completed = 2,
    Cancelled = 3,
    MyAssignments = 4
}

public static class ProductionWorkOrderTransferGrouping
{
    public const string UnlinkedPendingReassignmentDescriptionMarker = "iptal sonrası atanmaya açık";

    public sealed class LabelContext
    {
        public Dictionary<long, int> PartialTransferIndex { get; init; } = [];
        public HashSet<long> CurrentKalanHeaderIds { get; init; } = [];
    }

    public static string GetOrderKey(ProductionTransferHeaderLink link) =>
        link.ProductionOrderId?.ToString(CultureInfo.InvariantCulture)
        ?? link.ProductionHeaderId?.ToString(CultureInfo.InvariantCulture)
        ?? link.ProductionOrderNo?.Trim()
        ?? $"transfer:{link.WarehouseTransferHeaderId}";

    public static bool IsUnlinkedProductionTransfer(ProductionTransferHeaderLink link) =>
        !link.ProductionOrderId.HasValue
        && !link.ProductionHeaderId.HasValue
        && string.IsNullOrWhiteSpace(link.ProductionOrderNo);

    public static string? ResolveAtanmayanlarListingKey(
        ProductionTransferHeaderLink link,
        WarehouseTransferHeader header)
    {
        if (IsUnlinkedProductionTransfer(link)
            && link.AutoGenerated
            && link.ParentWarehouseTransferHeaderId.HasValue)
            return header.DocumentNo?.Trim();

        return link.ProductionOrderNo?.Trim()
            ?? header.ExternalReferenceNo?.Trim()
            ?? (IsUnlinkedProductionTransfer(link) ? header.DocumentNo?.Trim() : null);
    }

    public static bool IsCompletedTab(ProductionTransferHeaderLink link) =>
        link.WorkflowStatus is ProductionTransferWorkflowStatus.Completed
            or ProductionTransferWorkflowStatus.CompletedWithShortage;

    public static bool HasOpenCancellationReturn(WarehouseTransferHeader header) =>
        header.Tasks.Any(task => !task.IsDeleted
            && task.TaskType == WarehouseTransferTaskType.CancellationReturn
            && task.Status is not WarehouseTransferTaskStatus.Completed
                and not WarehouseTransferTaskStatus.Cancelled);

    public static bool MatchesTab(
        ProductionWorkOrderTransferTab tab,
        WarehouseTransferHeader header,
        ProductionTransferHeaderLink link)
    {
        var openCancellationReturn = HasOpenCancellationReturn(header);
        return tab switch
        {
            ProductionWorkOrderTransferTab.Completed => IsCompletedTab(link),
            ProductionWorkOrderTransferTab.Cancelled =>
                header.Status == WarehouseTransferStatus.Cancelled
                && !openCancellationReturn
                && !HasOnlyPostCancellationReturnUnassignedRemainder(header, link),
            ProductionWorkOrderTransferTab.Picking =>
                !IsCompletedTab(link)
                && !IsUnassignedOpenPartialTransferRemainder(header, link)
                && !(header.Status == WarehouseTransferStatus.Cancelled && !openCancellationReturn)
                && !HasOnlyPostCancellationReturnUnassignedRemainder(header, link),
            _ => false
        };
    }

    public static IQueryable<ProductionTransferHeaderLink> ApplyTabFilter(
        IQueryable<ProductionTransferHeaderLink> query,
        ProductionWorkOrderTransferTab tab,
        long? currentUserId = null,
        IReadOnlyCollection<long>? actorWarehouseIds = null)
    {
        var warehouseIds = actorWarehouseIds as long[] ?? actorWarehouseIds?.ToArray() ?? [];
        var warehouseRestricted = warehouseIds.Length > 0;
        return tab switch
        {
            ProductionWorkOrderTransferTab.Completed => query.Where(link =>
                link.WorkflowStatus == ProductionTransferWorkflowStatus.Completed
                || link.WorkflowStatus == ProductionTransferWorkflowStatus.CompletedWithShortage),
            ProductionWorkOrderTransferTab.Cancelled => query.Where(link =>
                link.WarehouseTransferHeader.Status == WarehouseTransferStatus.Cancelled
                && !link.WarehouseTransferHeader.Tasks.Any(task => !task.IsDeleted
                    && task.TaskType == WarehouseTransferTaskType.CancellationReturn
                    && task.Status != WarehouseTransferTaskStatus.Completed
                    && task.Status != WarehouseTransferTaskStatus.Cancelled)),
            ProductionWorkOrderTransferTab.Picking => query.Where(link =>
                link.WorkflowStatus != ProductionTransferWorkflowStatus.Completed
                && link.WorkflowStatus != ProductionTransferWorkflowStatus.CompletedWithShortage
                && !(link.AutoGenerated
                    && link.ParentWarehouseTransferHeaderId.HasValue
                    && link.WarehouseTransferHeader.Status != WarehouseTransferStatus.Cancelled
                    && link.WorkflowStatus != ProductionTransferWorkflowStatus.Cancelled
                    && !link.WarehouseTransferHeader.Tasks.Any(task => !task.IsDeleted
                        && task.Status != WarehouseTransferTaskStatus.Completed
                        && task.Status != WarehouseTransferTaskStatus.Cancelled
                        && (task.Assignments.Any(assignment => !assignment.IsDeleted)
                            || (task.TaskType == WarehouseTransferTaskType.Pick
                                && task.ReleasedToWarehousePool
                                && !task.Assignments.Any(assignment => !assignment.IsDeleted)))))
                && (link.WarehouseTransferHeader.Status != WarehouseTransferStatus.Cancelled
                    || link.WarehouseTransferHeader.Tasks.Any(task => !task.IsDeleted
                        && task.TaskType == WarehouseTransferTaskType.CancellationReturn
                        && task.Status != WarehouseTransferTaskStatus.Completed
                        && task.Status != WarehouseTransferTaskStatus.Cancelled))),
            // KKD Mine: kişiye atanmış açık görev VEYA (depo kısıtlı kullanıcı + açıkça havuza bırakılmış görev).
            ProductionWorkOrderTransferTab.MyAssignments => ApplyTabFilter(query, ProductionWorkOrderTransferTab.Picking, currentUserId, warehouseIds)
                .Where(link => link.WarehouseTransferHeader.Tasks.Any(task => !task.IsDeleted
                    && task.Status != WarehouseTransferTaskStatus.Completed
                    && task.Status != WarehouseTransferTaskStatus.Cancelled
                    && (task.Assignments.Any(assignment => !assignment.IsDeleted && assignment.UserId == currentUserId)
                        || (warehouseRestricted
                            && task.TaskType == WarehouseTransferTaskType.Pick
                            && !task.Assignments.Any(assignment => !assignment.IsDeleted)
                            && warehouseIds.Contains(task.WarehouseId)
                            && task.ReleasedToWarehousePool)))),
            _ => query
        };
    }

    /// <summary>
    /// Kullanıcının hâlâ üzerinde çalışabileceği (açık / devam eden) bir görev ataması var mı?
    /// Tamamlanmış veya iptal edilmiş görevlerde kalan atamalar Benim İşlerim'e dahil edilmez.
    /// </summary>
    public static bool HasActionableAssignmentForUser(WarehouseTransferTask task, long userId) =>
        !task.IsDeleted
        && task.Status is not WarehouseTransferTaskStatus.Completed
            and not WarehouseTransferTaskStatus.Cancelled
        && task.Assignments.Any(assignment => !assignment.IsDeleted && assignment.UserId == userId);

    /// <summary>
    /// Depoya bırakılmış, henüz kimseye bağlanmamış açık toplama görevi (KKD havuz görevinin karşılığı).
    /// Yalnızca release-to-pool ile işaretlenen işlerdir; kişiye/depoya atanmamış yeni kayıt Atanmayanlar’da kalır.
    /// </summary>
    public static bool IsWarehousePoolPickTask(
        WarehouseTransferTask task,
        ProductionTransferHeaderLink link,
        IReadOnlyList<WarehouseTransferTask> allTasks) =>
        task.ReleasedToWarehousePool
        && task.TaskType == WarehouseTransferTaskType.Pick
        && HasNoActiveAssignment(task)
        && IsOpenAtanmayanlarPickStatus(task)
        && IsAtanmayanlarEligiblePickStructure(task, link, allTasks);

    public static bool MatchesMyAssignments(
        WarehouseTransferHeader header,
        ProductionTransferHeaderLink link,
        long userId,
        IReadOnlyCollection<long>? actorWarehouseIds = null)
    {
        if (!MatchesTab(ProductionWorkOrderTransferTab.Picking, header, link)) return false;

        var tasks = header.Tasks.Where(task => !task.IsDeleted).ToArray();
        if (tasks.Any(task => HasActionableAssignmentForUser(task, userId))) return true;

        var warehouseIds = actorWarehouseIds ?? [];
        if (warehouseIds.Count == 0) return false;
        return tasks.Any(task =>
            IsWarehousePoolPickTask(task, link, tasks) && warehouseIds.Contains(task.WarehouseId));
    }

    public static bool MatchesSearch(string? search, WarehouseTransferHeader header, ProductionTransferHeaderLink link)
    {
        if (string.IsNullOrWhiteSpace(search)) return true;
        var term = search.Trim();
        return header.DocumentNo.Contains(term, StringComparison.OrdinalIgnoreCase)
            || (header.ExternalReferenceNo?.Contains(term, StringComparison.OrdinalIgnoreCase) ?? false)
            || (link.ProductionOrderNo?.Contains(term, StringComparison.OrdinalIgnoreCase) ?? false)
            || (header.ProjectCode?.Contains(term, StringComparison.OrdinalIgnoreCase) ?? false);
    }

    public static LabelContext BuildLabelContext(IEnumerable<ProductionTransferHeaderLink> links)
    {
        var partialIndexes = new Dictionary<long, int>();
        var kalanIds = new HashSet<long>();

        foreach (var group in links.GroupBy(GetOrderKey))
        {
            var groupLinks = group.ToList();
            var byHeaderId = groupLinks.ToDictionary(x => x.WarehouseTransferHeaderId);
            var roots = groupLinks.Where(link =>
                    !link.ParentWarehouseTransferHeaderId.HasValue
                    || !byHeaderId.ContainsKey(link.ParentWarehouseTransferHeaderId.Value))
                .ToArray();

            foreach (var root in roots)
            {
                var chain = BuildResidualChain(root, byHeaderId);
                if (chain.Count == 0) continue;

                var partialIndex = 0;
                for (var index = 0; index < chain.Count - 1; index++)
                {
                    var item = chain[index];
                    if (item.WorkflowStatus == ProductionTransferWorkflowStatus.CompletedWithShortage
                        && item.ResidualWarehouseTransferHeaderId.HasValue)
                    {
                        partialIndex++;
                        partialIndexes[item.WarehouseTransferHeaderId] = partialIndex;
                    }
                }

                if (chain.Count > 1 || chain[^1].ParentWarehouseTransferHeaderId.HasValue)
                    kalanIds.Add(chain[^1].WarehouseTransferHeaderId);
            }
        }

        return new LabelContext
        {
            PartialTransferIndex = partialIndexes,
            CurrentKalanHeaderIds = kalanIds
        };
    }

    public static string? GetDisplaySuffix(
        WarehouseTransferTask task,
        ProductionTransferHeaderLink link,
        LabelContext context,
        IReadOnlyList<WarehouseTransferTask> allTasks)
    {
        if (task.TaskType is WarehouseTransferTaskType.CancellationReturn)
            return null;

        if (context.PartialTransferIndex.TryGetValue(link.WarehouseTransferHeaderId, out var partialIndex))
            return partialIndex == 1 ? "-KISMITRANSFER" : $"-KISMITRANSFER-{partialIndex}";

        if (context.CurrentKalanHeaderIds.Contains(link.WarehouseTransferHeaderId)
            && task.TaskType == WarehouseTransferTaskType.Pick)
            return "-KALANTRANSFER";

        if (IsPostCancellationReturnUnassignedPickTask(task, allTasks))
            return "-IPTALIKALAN";

        return null;
    }

    public static string BuildCancellationReturnDisplayLabel(string taskNo, string documentNo)
    {
        const string marker = "-IPTALIADE";
        var markerIndex = taskNo.IndexOf(marker, StringComparison.OrdinalIgnoreCase);
        if (markerIndex < 0) return taskNo;

        var suffixPart = taskNo[(markerIndex + marker.Length)..];
        if (string.IsNullOrEmpty(suffixPart) || suffixPart == "1")
            return documentNo + marker;

        return taskNo;
    }

    public static string BuildDisplayLabel(string taskNo, string documentNo, string? displaySuffix)
    {
        if (string.IsNullOrEmpty(displaySuffix)) return taskNo;
        if (taskNo.Contains("-IADE", StringComparison.OrdinalIgnoreCase)) return taskNo;
        if (taskNo.Contains("-IPTALIADE", StringComparison.OrdinalIgnoreCase))
            return BuildCancellationReturnDisplayLabel(taskNo, documentNo);

        var prefix = documentNo + "-";
        if (taskNo.StartsWith(prefix, StringComparison.Ordinal)
            && int.TryParse(taskNo[prefix.Length..], NumberStyles.None, CultureInfo.InvariantCulture, out _))
            return documentNo + displaySuffix;

        return taskNo + displaySuffix;
    }

    /// <summary>Aktif atama yoksa (devir / iade sonrası) silinmiş atamaları gösterir.</summary>
    public static IReadOnlyList<string> ResolveAssignedUsernames(
        IEnumerable<WarehouseTransferTaskAssignment> assignments,
        IReadOnlyDictionary<long, string> users)
    {
        var assignmentRows = assignments as IReadOnlyCollection<WarehouseTransferTaskAssignment> ?? assignments.ToArray();
        var active = assignmentRows
            .Where(x => !x.IsDeleted)
            .OrderByDescending(x => x.IsPrimary)
            .ThenByDescending(x => x.AssignedAtUtc)
            .Select(x => users.GetValueOrDefault(x.UserId, $"Kullanıcı #{x.UserId}"))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();

        if (active.Length > 0) return active;

        return assignmentRows
            .Where(x => x.IsDeleted)
            .OrderByDescending(x => x.AssignedAtUtc)
            .Select(x => users.GetValueOrDefault(x.UserId, $"Kullanıcı #{x.UserId}"))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToArray();
    }

    public static bool IsPostCancellationReturnUnassignedPickTask(
        WarehouseTransferTask task,
        IReadOnlyList<WarehouseTransferTask> allTasks) =>
        IsCancellationReturnKalanPickTask(task, allTasks)
        && IsOpenAtanmayanlarPickStatus(task);

    public static bool IsUnlinkedReleasedDraftPickTask(
        WarehouseTransferTask task,
        ProductionTransferHeaderLink link) =>
        IsUnlinkedReleasedDraftPickStructure(task, link)
        && IsOpenAtanmayanlarPickStatus(task);

    public static bool IsUnassignedCreatedPickTask(
        WarehouseTransferTask task,
        ProductionTransferHeaderLink link,
        IReadOnlyList<WarehouseTransferTask> allTasks) =>
        IsUnassignedCreatedPickStructure(task, link, allTasks)
        && IsOpenAtanmayanlarPickStatus(task);

    public static bool IsAtanmayanlarUnassignedPickTask(
        WarehouseTransferTask task,
        ProductionTransferHeaderLink link,
        IReadOnlyList<WarehouseTransferTask> allTasks) =>
        !task.ReleasedToWarehousePool
        && (IsPostCancellationReturnUnassignedPickTask(task, allTasks)
            || IsUnlinkedReleasedDraftPickTask(task, link)
            || IsUnassignedCreatedPickTask(task, link, allTasks));

    public static bool IsCancellableAtanmayanlarPickTask(
        WarehouseTransferTask task,
        ProductionTransferHeaderLink link,
        IReadOnlyList<WarehouseTransferTask> allTasks) =>
        IsAtanmayanlarUnassignedPickTask(task, link, allTasks)
        || IsPostShortageHandoverUnassignedPickTask(task, link);

    public static bool IsRestorableAtanmayanlarPickTask(
        WarehouseTransferTask task,
        ProductionTransferHeaderLink link,
        IReadOnlyList<WarehouseTransferTask> allTasks) =>
        task.Status == WarehouseTransferTaskStatus.Cancelled
        && (IsCancellationReturnKalanPickTask(task, allTasks)
            || IsUnlinkedReleasedDraftPickStructure(task, link)
            || IsUnassignedCreatedPickStructure(task, link, allTasks)
            || IsPostShortageHandoverPickStructure(task, link));

    public static bool IsCancellationReturnKalanPickTask(
        WarehouseTransferTask task,
        IReadOnlyList<WarehouseTransferTask> allTasks) =>
        task.TaskType == WarehouseTransferTaskType.Pick
        && HasNoActiveAssignment(task)
        && task.PreviousTaskId is long cancellationReturnTaskId
        && allTasks.Any(other => !other.IsDeleted
            && other.TaskType == WarehouseTransferTaskType.CancellationReturn
            && other.Status == WarehouseTransferTaskStatus.Completed
            && other.Id == cancellationReturnTaskId);

    public static bool IsPostShortageHandoverUnassignedPickTask(
        WarehouseTransferTask task,
        ProductionTransferHeaderLink link) =>
        IsPostShortageHandoverPickStructure(task, link)
        && IsOpenAtanmayanlarPickStatus(task)
        && !task.ReleasedToWarehousePool;

    private static bool IsOpenAtanmayanlarPickStatus(WarehouseTransferTask task) =>
        task.Status is not WarehouseTransferTaskStatus.Completed
            and not WarehouseTransferTaskStatus.Cancelled;

    private static bool HasNoActiveAssignment(WarehouseTransferTask task) =>
        !task.Assignments.Any(assignment => !assignment.IsDeleted);

    private static bool IsUnlinkedReleasedDraftPickStructure(
        WarehouseTransferTask task,
        ProductionTransferHeaderLink link) =>
        IsUnlinkedProductionTransfer(link)
        && task.TaskType == WarehouseTransferTaskType.Pick
        && HasNoActiveAssignment(task)
        && (task.Description?.Contains(UnlinkedPendingReassignmentDescriptionMarker, StringComparison.OrdinalIgnoreCase) ?? false);

    private static bool IsPostShortageHandoverPickStructure(
        WarehouseTransferTask task,
        ProductionTransferHeaderLink link) =>
        task.TaskType == WarehouseTransferTaskType.Pick
        && HasNoActiveAssignment(task)
        && link.ParentWarehouseTransferHeaderId.HasValue
        && link.AutoGenerated;

    private static bool IsUnassignedCreatedPickStructure(
        WarehouseTransferTask task,
        ProductionTransferHeaderLink link,
        IReadOnlyList<WarehouseTransferTask> allTasks) =>
        task.TaskType == WarehouseTransferTaskType.Pick
        && HasNoActiveAssignment(task)
        && !IsCancellationReturnKalanPickTask(task, allTasks)
        && !IsUnlinkedReleasedDraftPickStructure(task, link)
        && !IsPostShortageHandoverPickStructure(task, link);

    private static bool IsAtanmayanlarEligiblePickStructure(
        WarehouseTransferTask task,
        ProductionTransferHeaderLink link,
        IReadOnlyList<WarehouseTransferTask> allTasks) =>
        IsCancellationReturnKalanPickTask(task, allTasks)
        || IsUnlinkedReleasedDraftPickStructure(task, link)
        || IsUnassignedCreatedPickStructure(task, link, allTasks)
        || IsPostShortageHandoverPickStructure(task, link);

    public static bool IsOpenPartialTransferRemainderLink(ProductionTransferHeaderLink link)
    {
        if (!link.AutoGenerated || !link.ParentWarehouseTransferHeaderId.HasValue) return false;
        if (link.WarehouseTransferHeader?.Status == WarehouseTransferStatus.Cancelled) return false;

        return link.WorkflowStatus is not ProductionTransferWorkflowStatus.Completed
            and not ProductionTransferWorkflowStatus.CompletedWithShortage
            and not ProductionTransferWorkflowStatus.Cancelled;
    }

    public static bool IsUnassignedOpenPartialTransferRemainder(
        WarehouseTransferHeader header,
        ProductionTransferHeaderLink link)
    {
        if (!IsOpenPartialTransferRemainderLink(link)) return false;
        if (HasActiveOpenTaskAssignment(header)) return false;

        var tasks = header.Tasks.Where(task => !task.IsDeleted).ToArray();
        return !tasks.Any(task => IsWarehousePoolPickTask(task, link, tasks));
    }

    public static bool HasActiveOpenTaskAssignment(WarehouseTransferHeader header) =>
        header.Tasks.Any(task => !task.IsDeleted
            && task.Status is not WarehouseTransferTaskStatus.Completed
                and not WarehouseTransferTaskStatus.Cancelled
            && task.Assignments.Any(assignment => !assignment.IsDeleted));

    public static ProductionTransferHeaderLink? ResolveLatestManualAssignmentLink(
        IEnumerable<ProductionTransferHeaderLink> links) =>
        links
            .Where(link => !link.AutoGenerated
                && link.WorkflowStatus != ProductionTransferWorkflowStatus.Cancelled
                && link.WarehouseTransferHeader?.Status != WarehouseTransferStatus.Cancelled)
            .OrderByDescending(link => link.WarehouseTransferHeader?.CreatedDate ?? link.CreatedDate)
            .ThenByDescending(link => link.WarehouseTransferHeaderId)
            .FirstOrDefault();

    public static bool BelongsToAssignmentLineage(
        ProductionTransferHeaderLink link,
        long manualRootHeaderId,
        IReadOnlyDictionary<long, ProductionTransferHeaderLink> linksByHeaderId)
    {
        if (link.WarehouseTransferHeaderId == manualRootHeaderId) return true;

        var currentParentId = link.ParentWarehouseTransferHeaderId;
        var visited = new HashSet<long>();
        while (currentParentId is long parentId && visited.Add(parentId))
        {
            if (parentId == manualRootHeaderId) return true;
            if (!linksByHeaderId.TryGetValue(parentId, out var parentLink)) return false;
            currentParentId = parentLink.ParentWarehouseTransferHeaderId;
        }

        return false;
    }

    public static IReadOnlyList<ProductionTransferHeaderLink> FilterActiveOpenPartialTransferRemainderLinks(
        IEnumerable<ProductionTransferHeaderLink> links)
    {
        var linkList = links as IReadOnlyList<ProductionTransferHeaderLink> ?? links.ToArray();
        var openRemainders = linkList.Where(IsOpenPartialTransferRemainderLink).ToArray();
        if (openRemainders.Length == 0) return [];

        var latestManual = ResolveLatestManualAssignmentLink(linkList);
        if (latestManual is null) return openRemainders;

        var byHeaderId = linkList
            .GroupBy(link => link.WarehouseTransferHeaderId)
            .ToDictionary(group => group.Key, group => group.First());
        var manualRootHeaderId = latestManual.WarehouseTransferHeaderId;

        return openRemainders
            .Where(link => BelongsToAssignmentLineage(link, manualRootHeaderId, byHeaderId))
            .ToArray();
    }

    public static bool IsProductionCancellationReturnTask(WarehouseTransferTask task) =>
        task.TaskType == WarehouseTransferTaskType.CancellationReturn
        && task.TaskNo.Contains("-IPTALIADE", StringComparison.OrdinalIgnoreCase);

    public static bool IsCancellationReturnEligibleForRemainderFlow(WarehouseTransferTask task) =>
        task.TaskType == WarehouseTransferTaskType.CancellationReturn;

    public static bool HasOnlyPostCancellationReturnUnassignedRemainder(
        WarehouseTransferHeader header,
        ProductionTransferHeaderLink link)
    {
        if (HasOpenCancellationReturn(header)) return false;
        if (IsOpenPartialTransferRemainderLink(link)) return false;

        var tasks = header.Tasks.Where(t => !t.IsDeleted).ToArray();
        var openTasks = tasks.Where(t => t.Status is not WarehouseTransferTaskStatus.Completed
            and not WarehouseTransferTaskStatus.Cancelled).ToArray();
        if (openTasks.Length == 0) return false;

        return openTasks.All(t => IsAtanmayanlarUnassignedPickTask(t, link, tasks));
    }

    private static List<ProductionTransferHeaderLink> BuildResidualChain(
        ProductionTransferHeaderLink root,
        IReadOnlyDictionary<long, ProductionTransferHeaderLink> byHeaderId)
    {
        var chain = new List<ProductionTransferHeaderLink> { root };
        var current = root;
        while (current.ResidualWarehouseTransferHeaderId is long residualId
            && byHeaderId.TryGetValue(residualId, out var next))
        {
            chain.Add(next);
            current = next;
        }

        return chain;
    }
}
