using verii_wms_api_v2.Modules.Shipping.Domain;
using verii_wms_api_v2.Modules.WarehouseOperations.Domain;
using verii_wms_api_v2.Shared;

namespace verii_wms_api_v2.Modules.Shipping.Application;

public sealed record ShipmentSourceRequest(string OrderNumber,string ExternalLineId,int? ExternalLineNo,string ExternalStockCode,string? ExternalYapCode,DateOnly? OrderDate,decimal OrderedQuantity,decimal PreviouslyShippedQuantity,decimal AvailableQuantity);
public sealed record ShipmentTrackingRequest(decimal Quantity,string? HandlingUnitNo,string? ContainerNo,string? LotNo,string? SerialNo,DateOnly? ManufacturingDate,DateOnly? ExpirationDate,long? SourceLocationId);
public sealed record ShipmentLineRequest(long StockId,long? YapCodeId,decimal Quantity,string? UnitCode,StockTrackingType TrackingType,bool RequireHandlingUnit,long? SourceLocationId,string? Description,IReadOnlyList<ShipmentTrackingRequest>? Trackings,ShipmentSourceRequest? Source);
public sealed record CreateShipmentDraftRequest(Guid IdempotencyKey,string BranchCode,long DocumentSeriesId,DateOnly DocumentDate,ShipmentInitiationMode InitiationMode,long CustomerId,long SourceWarehouseId,long? StagingLocationId,long? LoadingLocationId,DateTimeOffset? PlannedShipmentAtUtc,byte Priority,string? ExternalReferenceNo,bool IsEDispatch,string? CarrierCode,string? CarrierName,string? VehiclePlate,string? TrailerPlate,string? DriverName,string? SealNo,string? Description,IReadOnlyList<ShipmentLineRequest> Lines,IReadOnlyList<long>? AssignedUserIds);
public sealed record CreateShipmentDraftResult(long Id,string DocumentNo,int LineCount,decimal RequestedQuantity,bool Replayed,long? TaskId,string? TaskNo);
public sealed record UpdateShipmentDraftRequest(string RowVersion,DateOnly DocumentDate,long? StagingLocationId,long? LoadingLocationId,
    DateTimeOffset? PlannedShipmentAtUtc,byte Priority,string? ExternalReferenceNo,bool IsEDispatch,string? CarrierCode,
    string? CarrierName,string? VehiclePlate,string? TrailerPlate,string? DriverName,string? SealNo,string? Description);
public sealed record ShipmentGridRow(long Id,string BranchCode,string DocumentNo,DateOnly DocumentDate,ShipmentInitiationMode InitiationMode,ShipmentStatus Status,OperationApprovalStatus ApprovalStatus,ErpIntegrationStatus ErpIntegrationStatus,long CustomerId,string CustomerCode,string? CustomerName,long SourceWarehouseId,int SourceWarehouseCode,string SourceWarehouseName,int LineCount,decimal RequestedQuantity,decimal PickedQuantity,decimal PackedQuantity,decimal LoadedQuantity,decimal ShippedQuantity,byte Priority,DateTimeOffset? PlannedShipmentAtUtc,long? CreatedBy,DateTime? CreatedDate,long? UpdatedBy,DateTime? UpdatedDate);
public sealed record ShipmentDetailLine(long Id,int LineNo,long StockId,string StockCode,string? StockName,string? YapCode,string UnitCode,decimal RequestedQuantity,decimal ReservedQuantity,decimal PickedQuantity,decimal PackedQuantity,decimal LoadedQuantity,decimal ShippedQuantity,ShipmentLineStatus Status,int TrackingCount,StockTrackingType TrackingType,bool RequireHandlingUnit);
public sealed record ShipmentDraftMetadata(long? StagingLocationId,long? LoadingLocationId,string? ExternalReferenceNo,bool IsEDispatch,
    string? CarrierCode,string? CarrierName,string? VehiclePlate,string? TrailerPlate,string? DriverName,string? SealNo,string? Description);
public sealed record ShipmentDetail(ShipmentGridRow Header,IReadOnlyList<ShipmentDetailLine> Lines,string RowVersion,ShipmentDraftMetadata Draft);
public interface IShippingService{Task<CreateShipmentDraftResult>CreateDraftAsync(CreateShipmentDraftRequest request,long actor,CancellationToken ct=default);Task<PagedResponse<ShipmentGridRow>>GetPagedAsync(PagedRequest request,CancellationToken ct=default);Task<ShipmentDetail>GetDetailAsync(long id,CancellationToken ct=default);Task<ShipmentDetail>UpdateDraftAsync(long id,UpdateShipmentDraftRequest request,long actor,CancellationToken ct=default);Task DeleteDraftAsync(long id,long actor,CancellationToken ct=default);}

public sealed record ShipmentPolicyDto(long Id,string BranchCode,bool AllowOrderBasedTask,bool AllowStockBasedTask,bool AllowOrderBasedDirect,bool AllowStockBasedDirect,bool RequireApproval,bool RequireAssigneeForTask,bool AllowMultipleAssignees,bool AutoReleaseTaskBased,bool AllowPartialPicking,bool AllowPartialShipment,bool RequireSourceLocation,bool RequireShipmentInformation,bool RequireLoadingConfirmation,bool AutoPostErpAfterApproval,decimal MinimumFulfillmentPercent,decimal OverPickTolerancePercent,ShipmentReservationPolicy ReservationPolicy,ShipmentPackingPolicy PackingPolicy,ShipmentShortagePolicy ShortagePolicy,ShipmentOverPickPolicy OverPickPolicy,long? UpdatedBy,DateTime? UpdatedDate);
public sealed record UpdateShipmentPolicyRequest(string BranchCode,bool AllowOrderBasedTask,bool AllowStockBasedTask,bool AllowOrderBasedDirect,bool AllowStockBasedDirect,bool RequireApproval,bool RequireAssigneeForTask,bool AllowMultipleAssignees,bool AutoReleaseTaskBased,bool AllowPartialPicking,bool AllowPartialShipment,bool RequireSourceLocation,bool RequireShipmentInformation,bool RequireLoadingConfirmation,bool AutoPostErpAfterApproval,decimal MinimumFulfillmentPercent,decimal OverPickTolerancePercent,ShipmentReservationPolicy ReservationPolicy,ShipmentPackingPolicy PackingPolicy,ShipmentShortagePolicy ShortagePolicy,ShipmentOverPickPolicy OverPickPolicy);
public interface IShipmentPolicyService{Task<ShipmentPolicyDto>GetAsync(string branchCode,CancellationToken ct=default);Task<ShipmentPolicyDto>UpdateAsync(UpdateShipmentPolicyRequest request,long actor,CancellationToken ct=default);}
