using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using verii_wms_api_v2.Modules.Shipping.Domain;
using verii_wms_api_v2.Shared.Infrastructure;

namespace verii_wms_api_v2.Modules.Shipping.Infrastructure;

public sealed class ShipmentHeaderConfiguration:BaseEntityConfiguration<ShipmentHeader>{
 protected override void ConfigureEntity(EntityTypeBuilder<ShipmentHeader>b){b.ToTable("RII_SH_HEADER");b.Property(x=>x.DocumentNo).HasMaxLength(50).IsRequired();b.Property(x=>x.CustomerCodeSnapshot).HasMaxLength(100).IsRequired();b.Property(x=>x.CustomerNameSnapshot).HasMaxLength(300);b.Property(x=>x.ExternalReferenceNo).HasMaxLength(100);b.Property(x=>x.WaybillNo).HasMaxLength(50);b.Property(x=>x.CarrierCode).HasMaxLength(50);b.Property(x=>x.CarrierName).HasMaxLength(200);b.Property(x=>x.VehiclePlate).HasMaxLength(20);b.Property(x=>x.TrailerPlate).HasMaxLength(20);b.Property(x=>x.DriverName).HasMaxLength(200);b.Property(x=>x.SealNo).HasMaxLength(50);b.Property(x=>x.TrackingNo).HasMaxLength(100);b.Property(x=>x.Description).HasMaxLength(2000);b.Property(x=>x.ReservationPolicy).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.PackingPolicy).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.ShortagePolicy).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.OverPickPolicy).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.MinimumFulfillmentPercent).HasPrecision(9,4);b.Property(x=>x.OverPickTolerancePercent).HasPrecision(9,4);b.Property(x=>x.RowVersion).IsRowVersion();b.HasIndex(x=>new{x.BranchCode,x.DocumentNo}).IsUnique();b.HasIndex(x=>x.CorrelationId).IsUnique();b.HasIndex(x=>new{x.BranchCode,x.Status,x.PlannedShipmentAtUtc});}}
public sealed class ShipmentSourceDocumentConfiguration:BaseEntityConfiguration<ShipmentSourceDocument>{protected override void ConfigureEntity(EntityTypeBuilder<ShipmentSourceDocument>b){b.ToTable("RII_SH_SOURCE_DOCUMENT");b.Property(x=>x.SourceDocumentType).HasMaxLength(50).IsRequired();b.Property(x=>x.ExternalDocumentNo).HasMaxLength(100).IsRequired();b.Property(x=>x.ExternalDocumentId).HasMaxLength(100);b.Property(x=>x.ExternalStatus).HasMaxLength(50);b.HasOne(x=>x.Header).WithMany(x=>x.SourceDocuments).HasForeignKey(x=>x.ShipmentHeaderId).OnDelete(DeleteBehavior.Restrict);b.HasIndex(x=>new{x.ShipmentHeaderId,x.SourceDocumentType,x.ExternalDocumentNo}).IsUnique();}}
public sealed class ShipmentLineConfiguration:BaseEntityConfiguration<ShipmentLine>{protected override void ConfigureEntity(EntityTypeBuilder<ShipmentLine>b){b.ToTable("RII_SH_LINE",t=>t.HasCheckConstraint("CK_RII_SH_LINE_QTY","[RequestedQuantity] > 0 AND [ReservedQuantity] >= 0 AND [PickedQuantity] >= 0 AND [PackedQuantity] >= 0 AND [LoadedQuantity] >= 0 AND [ShippedQuantity] >= 0 AND [ShortClosedQuantity] >= 0"));b.Property(x=>x.StockCodeSnapshot).HasMaxLength(100).IsRequired();b.Property(x=>x.StockNameSnapshot).HasMaxLength(300);b.Property(x=>x.YapCodeSnapshot).HasMaxLength(100);b.Property(x=>x.UnitCode).HasMaxLength(20).IsRequired();foreach(var p in new[]{nameof(ShipmentLine.RequestedQuantity),nameof(ShipmentLine.ReservedQuantity),nameof(ShipmentLine.PickedQuantity),nameof(ShipmentLine.PackedQuantity),nameof(ShipmentLine.LoadedQuantity),nameof(ShipmentLine.ShippedQuantity),nameof(ShipmentLine.ShortClosedQuantity)})b.Property(p).HasPrecision(20,6);b.Property(x=>x.Description).HasMaxLength(1000);b.Property(x=>x.RowVersion).IsRowVersion();b.HasOne(x=>x.Header).WithMany(x=>x.Lines).HasForeignKey(x=>x.ShipmentHeaderId).OnDelete(DeleteBehavior.Restrict);b.HasIndex(x=>new{x.ShipmentHeaderId,x.LineNo}).IsUnique();}}
public sealed class ShipmentLineSourceConfiguration:BaseEntityConfiguration<ShipmentLineSource>{protected override void ConfigureEntity(EntityTypeBuilder<ShipmentLineSource>b){b.ToTable("RII_SH_LINE_SOURCE");b.Property(x=>x.ExternalLineId).HasMaxLength(100).IsRequired();b.Property(x=>x.ExternalStockCode).HasMaxLength(100).IsRequired();b.Property(x=>x.ExternalYapCode).HasMaxLength(100);b.Property(x=>x.UnitCode).HasMaxLength(20).IsRequired();b.Property(x=>x.OrderedQuantity).HasPrecision(20,6);b.Property(x=>x.PreviouslyShippedQuantity).HasPrecision(20,6);b.Property(x=>x.AllocatedQuantity).HasPrecision(20,6);b.HasOne(x=>x.Line).WithMany(x=>x.Sources).HasForeignKey(x=>x.ShipmentLineId).OnDelete(DeleteBehavior.Restrict);b.HasOne(x=>x.SourceDocument).WithMany(x=>x.LineSources).HasForeignKey(x=>x.ShipmentSourceDocumentId).OnDelete(DeleteBehavior.Restrict);b.HasIndex(x=>new{x.ShipmentLineId,x.ShipmentSourceDocumentId,x.ExternalLineId}).IsUnique();b.HasIndex(x=>new{x.ShipmentSourceDocumentId,x.ExternalLineId});}}
public sealed class ShipmentTrackingConfiguration:BaseEntityConfiguration<ShipmentTracking>{protected override void ConfigureEntity(EntityTypeBuilder<ShipmentTracking>b){b.ToTable("RII_SH_TRACKING",t=>t.HasCheckConstraint("CK_RII_SH_TRACKING_QTY","[PlannedQuantity] > 0 AND [ReservedQuantity] >= 0 AND [PickedQuantity] >= 0 AND [PackedQuantity] >= 0 AND [LoadedQuantity] >= 0 AND [ShippedQuantity] >= 0"));b.Property(x=>x.HandlingUnitNo).HasMaxLength(100);b.Property(x=>x.ContainerNo).HasMaxLength(100);b.Property(x=>x.LotNo).HasMaxLength(100);b.Property(x=>x.SerialNo).HasMaxLength(200);foreach(var p in new[]{nameof(ShipmentTracking.PlannedQuantity),nameof(ShipmentTracking.ReservedQuantity),nameof(ShipmentTracking.PickedQuantity),nameof(ShipmentTracking.PackedQuantity),nameof(ShipmentTracking.LoadedQuantity),nameof(ShipmentTracking.ShippedQuantity)})b.Property(p).HasPrecision(20,6);b.Property(x=>x.RowVersion).IsRowVersion();b.HasOne(x=>x.Line).WithMany(x=>x.Trackings).HasForeignKey(x=>x.ShipmentLineId).OnDelete(DeleteBehavior.Restrict);b.HasIndex(x=>new{x.ShipmentLineId,x.SerialNo});}}
public sealed class ShipmentTaskConfiguration:BaseEntityConfiguration<ShipmentTask>{protected override void ConfigureEntity(EntityTypeBuilder<ShipmentTask>b){b.ToTable("RII_SH_TASK");b.Property(x=>x.TaskNo).HasMaxLength(50).IsRequired();b.Property(x=>x.RowVersion).IsRowVersion();b.HasOne(x=>x.Header).WithMany(x=>x.Tasks).HasForeignKey(x=>x.ShipmentHeaderId).OnDelete(DeleteBehavior.Restrict);b.HasIndex(x=>new{x.BranchCode,x.TaskNo}).IsUnique();}}
public sealed class ShipmentTaskLineConfiguration:BaseEntityConfiguration<ShipmentTaskLine>{protected override void ConfigureEntity(EntityTypeBuilder<ShipmentTaskLine>b){b.ToTable("RII_SH_TASK_LINE",t=>t.HasCheckConstraint("CK_RII_SH_TASK_LINE_QTY","[PlannedQuantity] > 0 AND [ProcessedQuantity] >= 0"));b.Property(x=>x.PlannedQuantity).HasPrecision(20,6);b.Property(x=>x.ProcessedQuantity).HasPrecision(20,6);b.Property(x=>x.RowVersion).IsRowVersion();b.HasOne(x=>x.Task).WithMany(x=>x.Lines).HasForeignKey(x=>x.ShipmentTaskId).OnDelete(DeleteBehavior.Restrict);b.HasOne(x=>x.Line).WithMany(x=>x.TaskLines).HasForeignKey(x=>x.ShipmentLineId).OnDelete(DeleteBehavior.Restrict);b.HasIndex(x=>new{x.ShipmentTaskId,x.ShipmentLineId}).IsUnique();}}
public sealed class ShipmentTaskAssignmentConfiguration:BaseEntityConfiguration<ShipmentTaskAssignment>{protected override void ConfigureEntity(EntityTypeBuilder<ShipmentTaskAssignment>b){b.ToTable("RII_SH_TASK_ASSIGNMENT");b.HasOne(x=>x.Task).WithMany(x=>x.Assignments).HasForeignKey(x=>x.ShipmentTaskId).OnDelete(DeleteBehavior.Restrict);b.HasIndex(x=>new{x.ShipmentTaskId,x.UserId}).IsUnique();}}
public sealed class ShipmentStatusHistoryConfiguration:BaseEntityConfiguration<ShipmentStatusHistory>{protected override void ConfigureEntity(EntityTypeBuilder<ShipmentStatusHistory>b){b.ToTable("RII_SH_STATUS_HISTORY");b.Property(x=>x.FromStatus).HasMaxLength(50);b.Property(x=>x.ToStatus).HasMaxLength(50).IsRequired();b.Property(x=>x.Description).HasMaxLength(1000);b.HasOne(x=>x.Header).WithMany(x=>x.StatusHistory).HasForeignKey(x=>x.ShipmentHeaderId).OnDelete(DeleteBehavior.Restrict);b.HasIndex(x=>new{x.ShipmentHeaderId,x.ChangedAtUtc});}}
public sealed class ShipmentPolicyConfiguration:BaseEntityConfiguration<ShipmentPolicy>{protected override void ConfigureEntity(EntityTypeBuilder<ShipmentPolicy>b){b.ToTable("RII_SH_POLICIES",t=>{t.HasCheckConstraint("CK_RII_SH_POLICY_FULFILLMENT","[MinimumFulfillmentPercent] >= 0 AND [MinimumFulfillmentPercent] <= 100");t.HasCheckConstraint("CK_RII_SH_POLICY_OVERPICK","[OverPickTolerancePercent] >= 0 AND [OverPickTolerancePercent] <= 100");});b.Property(x=>x.PolicyKey).HasMaxLength(30).IsRequired();b.Property(x=>x.ReservationPolicy).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.PackingPolicy).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.ShortagePolicy).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.OverPickPolicy).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.MinimumFulfillmentPercent).HasPrecision(9,4);b.Property(x=>x.OverPickTolerancePercent).HasPrecision(9,4);b.Property(x=>x.RowVersion).IsRowVersion();b.HasIndex(x=>new{x.BranchCode,x.PolicyKey}).IsUnique().HasFilter("[IsDeleted] = 0");}}
